### ISSUE TITLE
npm init slidev Error 

### ISSUE THREAD

**Issue by forrany** [slidevjs/slidev#1043]
**Describe the bug**

I started up the project by 'npm init slidev@latest' and installed all dependencies
when I enter 'npm run dev'， the project just crash and console throw a error : Cannot create property '/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/theme-seriph/setup/shiki.ts' on string '/var/folders/md/kn4r376n5vzcx81xrnxq4h0r0000gn/T/node-jiti'
```
TypeError: Cannot create property '/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/theme-seriph/setup/shiki.ts' on string '/var/folders/md/kn4r376n5vzcx81xrnxq4h0r0000gn/T/node-jiti'
    at evalModule (/Users/vincentko/Desktop/slidev/slidev/node_modules/jiti/dist/jiti.js:1:254815)
    at jiti (/Users/vincentko/Desktop/slidev/slidev/node_modules/jiti/dist/jiti.js:1:253034)
    at loadSetups (/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/cli/dist/chunk-KKGXM3XL.js:23:73)
    at async createMarkdownPlugin (/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/cli/dist/chunk-GPOP6RE3.js:1316:26)
    at async ViteSlidevPlugin (/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/cli/dist/chunk-GPOP6RE3.js:1558:26)
    at async createServer (/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/cli/dist/chunk-35XQHQN5.js:2492:11)
    at async initServer (/Users/vincentko/Desktop/slidev/slidev/node_modules/@slidev/cli/dist/cli.js:117:16)

Node.js v18.7.0

```
**To Reproduce**
You can reproduce online ,just click here https://sli.dev/new

<img width="2434" alt="image" src="https://github.com/slidevjs/slidev/assets/29779326/df2aaa1b-790e-4725-bedd-1d74ca070185">

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome
 - Slidev version:  0.42.5

**Comment by antfu** [comment]
This should be fixed.
