### ISSUE TITLE
Error with installer generated slides.md using inline styles

### ISSUE THREAD

**Issue by tombruijn** [slidevjs/slidev#1081]
**Describe the bug**
The `slides.md` created by the slidev installer does not want to compile/render.
The included inline styles don't seem to be working.

```
[postcss] /@slidev/slides/2.md?vue&type=style&index=0&scoped=ae5e7f61&lang.css:9:2: Unknown word
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word (x2)
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word (x3)
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word (x4)
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word (x5)
[postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word (x6)
9:25:16 PM [vite] Internal server error: [postcss] /@slidev/slides/2.md?vue&type=style&index=0&scoped=ae5e7f61&lang.css:9:2: Unknown word
  Plugin: vite:css
  File: /@slidev/slides/2.md?vue&type=style&index=0&scoped=ae5e7f61&lang.css:9:2
  7  |  -webkit-text-fill-color: transparent;
  8  |  -moz-text-fill-color: transparent;
  9  |  }</p>
     |    ^
  10 |  </div></template>
  11 |  <script setup>
      at Input.error (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:588:22)
      at Parser.other (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:430:12)
      at Parser.parse (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:465:16)
      at parse (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///Users/tombruijn/tombruijn/projects/testslides/node_modules/vite/dist/node/chunks/dep-df561101.js:38868:63)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///Users/tombruijn/tombruijn/projects/testslides/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)
9:25:16 PM [vite] Internal server error: [postcss] /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2: Unknown word
  Plugin: vite:css
  File: /@slidev/slides/5.md?vue&type=style&index=0&scoped=90fd6163&lang.css:9:2
  7  |  .footnote-backref {
  8  |  display: none;
  9  |  }</p>
     |    ^
  10 |  </div></template>
  11 |  <script setup>
      at Input.error (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:588:22)
      at Parser.other (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:430:12)
      at Parser.parse (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parser.js:465:16)
      at parse (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/Users/tombruijn/tombruijn/projects/testslides/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///Users/tombruijn/tombruijn/projects/testslides/node_modules/vite/dist/node/chunks/dep-df561101.js:38868:63)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///Users/tombruijn/tombruijn/projects/testslides/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)
```

The code in question from `slides.md`:

```html
<style>
h1 {
  background-color: #2B90B6;
  background-image: linear-gradient(45deg, #4EC5D4 10%, #146b8c 20%);
  background-size: 100%;
  -webkit-background-clip: text;
  -moz-background-clip: text;
  -webkit-text-fill-color: transparent;
  -moz-text-fill-color: transparent;
}
</style>
```
and
```html
<style>
.footnotes-sep {
  @apply mt-20 opacity-10;
}
.footnotes {
  @apply text-sm opacity-75;
}
.footnote-backref {
  display: none;
}
</style>
```

Removing both inline styles included in the installer created `slides.md` file fixes the error, but I can't use inline styles.

Similar issue to #954, but happening on the latest version at time of writing.

Tested on the following versions:

- 0.42.8: error
- 0.42.7: error
- 0.42.0: error
- 0.41.1: no error (run `npm init slidev@0.41.1`)
- 0.41.0: no error

**To Reproduce**
1. `npm init slidev` (the latest version at time of writing)
2. Enter project name: "testslides"
3. Install and start now? `Y`
4. Choose the agent `npm` (same behavior with `yarn`)
5. After installation and directly after upon start it prints the error shown above in the terminal output and shows an empty page on the newly opened browser tab.

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Browser: Firefox 116.0.2 
 - Slidev version: 0.42.8

**Comment by very-doge-wow** [comment]
I am experiencing (I believe) the same issue with inline CSS:

```sh
16:26:06 [vite] Internal server error: [postcss] /@slidev/slides/6.md?vue&type=style&index=0&scoped=9bd6e946&lang.css:3:2: Unknown word
  Plugin: vite:css
  File: /@slidev/slides/6.md?vue&type=style&index=0&scoped=9bd6e946&lang.css:3:2
  1  |  <template><div><p>table {
  2  |  font-size: 50%;
  3  |  }</p>
     |    ^
  4  |  </div></template>
  5  |  <script setup>
      at Input.error (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/parser.js:588:22)
      at Parser.other (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/parser.js:430:12)
      at Parser.parse (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/parser.js:465:16)
      at parse (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/vite/dist/node/chunks/dep-df561101.js:38868:63)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///Users/very-doge-wow/Documents/GitLab_Projects/slidev/node_modules/vite/dist/node/chunks/dep-df561101.js:38266:56)

```

**Comment by ap-1** [comment]
Possibly related: I had an existing project with inline styles that no longer builds, no changes were made to the code. I can't create a minimal repro because I can't init a new project

**Comment by tombruijn** [comment]
Any luck with running 0.41.1? I am able use inline styles on that older version.

**Comment by very-doge-wow** [comment]
`0.42.7` worked for me. My build broke with the update to `0.42.8`.

**Comment by jneless** [comment]
+1

**Comment by AlbertBrand** [comment]
Seems the minor dependency upgrade caused this. The release has failing Cypress tests: https://github.com/slidevjs/slidev/actions/runs/5869567089/job/15914814786

**Comment by pposca** [comment]
This one is already solved, isn't it?

**Comment by tombruijn** [comment]
Works for me on the latest version 0.42.9. Closing.
