### ISSUE TITLE
Fails when open slidev

### ISSUE THREAD

**Issue by JesseJeson** [slidevjs/slidev#1088]
**Describe the bug**
It happens when I create slidev then open it in browser.

**Log**
```bash
ENOENT: no such file or directory, open '/@slidev/slides/1.md'
ENOENT: no such file or directory, open '/@slidev/slides/2.md'
ENOENT: no such file or directory, open '/@slidev/slides/3.md'
ENOENT: no such file or directory, open '/@slidev/slides/4.md'
ENOENT: no such file or directory, open '/@slidev/slides/5.md'
ENOENT: no such file or directory, open '/@slidev/slides/6.md'
ENOENT: no such file or directory, open '/@slidev/slides/7.md'
ENOENT: no such file or directory, open '/@slidev/slides/8.md'
ENOENT: no such file or directory, open '/@slidev/slides/9.md'
ENOENT: no such file or directory, open '/@slidev/slides/10.md'
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/1.md'
  Plugin: vite:vue
  File: /@slidev/slides/1.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
ENOENT: no such file or directory, open '/@slidev/slides/1.md'
ENOENT: no such file or directory, open '/@slidev/slides/2.md'
ENOENT: no such file or directory, open '/@slidev/slides/3.md'
ENOENT: no such file or directory, open '/@slidev/slides/4.md'
ENOENT: no such file or directory, open '/@slidev/slides/5.md'
ENOENT: no such file or directory, open '/@slidev/slides/6.md'
ENOENT: no such file or directory, open '/@slidev/slides/7.md'
ENOENT: no such file or directory, open '/@slidev/slides/8.md'
ENOENT: no such file or directory, open '/@slidev/slides/9.md'
ENOENT: no such file or directory, open '/@slidev/slides/10.md'
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/2.md'
  Plugin: vite:vue
  File: /@slidev/slides/2.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/3.md'
  Plugin: vite:vue
  File: /@slidev/slides/3.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/4.md'
  Plugin: vite:vue
  File: /@slidev/slides/4.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/5.md'
  Plugin: vite:vue
  File: /@slidev/slides/5.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/6.md'
  Plugin: vite:vue
  File: /@slidev/slides/6.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/7.md'
  Plugin: vite:vue
  File: /@slidev/slides/7.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/8.md'
  Plugin: vite:vue
  File: /@slidev/slides/8.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/9.md'
  Plugin: vite:vue
  File: /@slidev/slides/9.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
09:32:35 [vite] Internal server error: ENOENT: no such file or directory, open '/@slidev/slides/10.md'
  Plugin: vite:vue
  File: /@slidev/slides/10.md
      at Object.openSync (node:fs:601:3)
      at Object.readFileSync (node:fs:469:35)
      at getDescriptor (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:110:19)
      at transformMain (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2281:3)
      at TransformContext.transform (C:\Users\admin\AppData\Local\Yarn\Data\global\node_modules\@vitejs\plugin-vue\dist\index.cjs:2802:16)
      at Object.transform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///C:/Users/admin/AppData/Local/Yarn/Data/global/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
ENOENT: no such file or directory, open '/@slidev/slides/1.md'
ENOENT: no such file or directory, open '/@slidev/slides/2.md'
ENOENT: no such file or directory, open '/@slidev/slides/3.md'
ENOENT: no such file or directory, open '/@slidev/slides/4.md'
ENOENT: no such file or directory, open '/@slidev/slides/5.md'
ENOENT: no such file or directory, open '/@slidev/slides/6.md'
ENOENT: no such file or directory, open '/@slidev/slides/7.md'
ENOENT: no such file or directory, open '/@slidev/slides/8.md'
ENOENT: no such file or directory, open '/@slidev/slides/9.md'
ENOENT: no such file or directory, open '/@slidev/slides/10.md'
```
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Slidev version: 0.42.5

**Comment by JesseJeson** [comment]
After setting vitejs/plugin-vue back to version 4.2.3, it was solved
