### ISSUE TITLE
Unable to slidev (dev) on M2 Mac inside colima

### ISSUE THREAD

**Issue by openscript** [slidevjs/slidev#1116]
**Describe the bug**
I'm unable to develop a slidev presentation on Mac OS with colima inside a dev container:

```
root ➜ /workspaces/slidev-theme (main) $ yarn dev
yarn run v1.22.19
$ slidev example.md --open


  ●■▲
  Slidev  v0.43.1 

  theme       ./
  css engine  unocss
  entry       /workspaces/slidev-theme/example.md

  public slide show   > http://localhost:3030/
  presenter mode      > http://localhost:3030/presenter/
  remote control      > pass --remote to enable

  shortcuts           > restart | open | edit | quit
The service was stopped
The service was stopped (x2)
The service was stopped (x3)
The service was stopped (x4)
The service was stopped (x5)
The service was stopped (x6)
The service was stopped (x7)
The service was stopped (x8)
The service was stopped (x9)
The service was stopped (x10)
The service was stopped (x11)
The service was stopped (x12)
3:31:10 AM [vite] Internal server error: The service was stopped
  Plugin: vite:esbuild
  File: /workspaces/slidev-theme/node_modules/@slidev/client/setup/root.ts?v=3f3fadad
      at /workspaces/slidev-theme/node_modules/esbuild/lib/main.js:826:29
      at responseCallbacks.<computed> (/workspaces/slidev-theme/node_modules/esbuild/lib/main.js:703:9)
      at Socket.afterClose (/workspaces/slidev-theme/node_modules/esbuild/lib/main.js:693:28)
      at Socket.emit (node:events:526:35)
      at endReadableNT (node:internal/streams/readable:1376:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
The service was stopped
The service was stopped (x2)
The service was stopped (x3)
The service was stopped (x4)
The service was stopped (x5)
The service was stopped (x6)
The service was stopped (x7)
The service was stopped (x8)
The service was stopped (x9)
The service was stopped (x10)
The service was stopped (x11)
The service was stopped (x12)
The service was stopped (x13)
The service was stopped (x14)
The service was stopped (x15)
The service was stopped (x16)
The service was stopped (x17)
The service was stopped (x18)
/workspaces/slidev-theme/node_modules/esbuild/lib/main.js:1110
                    reject(new Error(error2));
                           ^

Error: The service was stopped
    at /workspaces/slidev-theme/node_modules/esbuild/lib/main.js:1110:28
    at responseCallbacks.<computed> (/workspaces/slidev-theme/node_modules/esbuild/lib/main.js:703:9)
    at Socket.afterClose (/workspaces/slidev-theme/node_modules/esbuild/lib/main.js:693:28)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1376:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. Clone https://github.com/openscript-ch/slidev-theme/
2. Open its devcontainer on a arm64 system with colima
3. Run `yarn dev`

**Desktop (please complete the following information):**
 - OS: colima 0.5.5 on Darwin freddy.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 arm64
 - Browser: Firefox 117.0
 - Slidev version: 0.43.1

**Comment by antfu** [comment]
I have zero knowledge with colima. As Slidev works fine outside of it, I suppose it's more like a colima compatibility issue? Or if there is anything we could do better on our side, feel free to investigate and send PRs. I many not be able to offer any help directly with your setup unfortunately.

**Comment by openscript** [comment]
> I have zero knowledge with colima. As Slidev works fine outside of it, I suppose it's more like a colima compatibility issue? Or if there is anything we could do better on our side, feel free to investigate and send PRs. I many not be able to offer any help directly with your setup unfortunately.

I understand and I think you are right. I'll close the issue and if I find a solution I'll post an update.

**Comment by openscript** [comment]
I've migrated from Colima to Docker Desktop and everything works now. You are right, it's a colima issue.
