### ISSUE TITLE
Error on preparser loading

### ISSUE THREAD

**Issue by aeudes** [slidevjs/slidev#1167]
**Describe the bug**
presentation did not run if we place a `preparser.ts` 

**To Reproduce**
1. npm init slidev
2. add `preparser.ts` in setup directory with following minimal content:
```
import { definePreparserSetup } from '@slidev/types'

export default definePreparserSetup(() => {
  return [
    {
      transformRawLines(lines) {

      }
    },
  ]
})
```
3. start slidev
`npm run dev `
4. See the error
``` 
node:internal/modules/cjs/loader:415
      const err = new Error(
                  ^

Error: Cannot find module '/home/alex/test_pres/test/slidev/node_modules/@slidev/types/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:415:19)
    at Module._findPath (node:internal/modules/cjs/loader:665:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at _resolve (/home/alex/test_pres/test/slidev/node_modules/jiti/dist/jiti.js:1:250334)
    at jiti (/home/alex/test_pres/test/slidev/node_modules/jiti/dist/jiti.js:1:252917)
    at /home/alex/test_pres/test/slidev/setup/preparser.ts:1:176
    at evalModule (/home/alex/test_pres/test/slidev/node_modules/jiti/dist/jiti.js:1:255614)
    at jiti (/home/alex/test_pres/test/slidev/node_modules/jiti/dist/jiti.js:1:253542)
    at loadSetups (file:///home/alex/test_pres/test/slidev/node_modules/@slidev/cli/dist/chunk-CYLMMBRG.mjs:24:70) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/alex/test_pres/test/slidev/node_modules/@slidev/types/package.json',
  requestPath: '@slidev/types'
}
```

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: chromium 117.0.5938.88
 - Slidev version:  v0.43.12

**Comment by pposca** [comment]
Same issue here. from release v0.43.9

**Comment by adamdehaven** [comment]
I'm able to fix this locally by changing the default `module` export file extension [on this line](https://github.com/slidevjs/slidev/blob/62a9fc6c6d0a4b98a321e4f5d210ae85850fa8ec/packages/types/package.json#L14) to `index.mjs` (since this file actually exists in the `dist/` directory for the `@slidev/types` package.

I believe the breakage originates from this commit: https://github.com/slidevjs/slidev/commit/c3a24c0566c3808ec0b110391f197dd89c824a4b#r131302664

**Comment by adamdehaven** [comment]
@antfu either the `cjs` entry needs to be restored or the `main` exports in the types package needs to be modified

**Comment by adamdehaven** [comment]
Put up a PR that should resolve the entry file; please verify before merging
