### ISSUE TITLE
Build still failing when installing slidev globally

### ISSUE THREAD

**Issue by Bibin112358** [slidevjs/slidev#1188]
**Describe the bug**
Same problem as https://github.com/slidevjs/slidev/issues/1115, but with the Slidev Version v0.43.15.
If you install slidev globally, when build SPA by running command slidev build, there is an error raised

```
$ ~/m/slidev_global_playground> slidev build

  ●■▲
  Slidev  v0.43.15 (global)

  theme       @slidev/theme-default
  css engine  unocss
  entry       /home/.../slidev_global_playground/slides.md
(node:28201) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
vite v4.5.0 building for production...
✓ 4 modules transformed.
✓ built in 172ms
[vite]: Rollup failed to resolve import "@unocss/reset/tailwind.css" from "/@slidev/styles".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "@unocss/reset/tailwind.css" from "/@slidev/styles".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///usr/local/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///usr/local/lib/node_modules/@slidev/cli/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  watchFiles: [
    '/home/.../slidev_global_playground/index.html',
    '\x00vite/modulepreload-polyfill',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/main.ts',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/vue/dist/vue.esm-browser.js',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@unhead/vue/dist/index.mjs',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/App.vue',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/setup/main.ts',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/routes.ts',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/modules/directives.ts',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/modules/context.ts',
    '/@slidev/styles',
    '/__uno_preflights.css',
    '/__uno_typography.css',
    '/__uno_shortcuts.css',
    '/__uno.css',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/styles/vars.css',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/styles/index.css',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/styles/code.css',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/styles/katex.css',
    '/usr/local/lib/node_modules/@slidev/cli/node_modules/@slidev/client/styles/transitions.css',
    '/usr/local/lib/node_modules/@slidev/theme-default/styles/index.ts'
  ]
}

```

**To Reproduce**

1. install slidev globally, `sudo npm i -g @slidev/cli`
2. Create a slides.md, `touch slides.md` (and copying something from https://sli.dev/)
3. Build it by running `slidev build`

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser: Firefox Browser 119.0 (64-bit)
 - Slidev version: 0.43.15

**Comment by Moanrisy** [comment]
Still happen to using v0.44.0

```
[mars@my_arch_linux ppt]$ slidev build
(node:11617) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Plea
se use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)


  ●■▲
  Slidev  v0.44.0 (global)

  theme       @slidev/theme-default
  css engine  unocss
  entry       /run/media/mars/4952045c-daeb-4253-b18c-e79f4fa83eb9/Projects/skripsi/
ppt/slides.md
vite v4.5.0 building for production...
✓ 4 modules transformed.
✓ built in 107ms
[vite]: Rollup failed to resolve import "@unocss/reset/tailwind.css" from "/@slidev/
styles".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "@unocss/reset/tailwind.css" from "/@
slidev/styles".
```

**Comment by KermanX** [comment]
It seems that this has been fixed by https://github.com/slidevjs/slidev/commit/2a152cf3c5915bf7f0409f6d71b4d3367964966a.
