### ISSUE TITLE
Build with public assets fails

### ISSUE THREAD

**Issue by d-koppenhagen** [slidevjs/slidev#1203]
**Describe the bug**

Hey, I have a custom slidev theme which I deployed on an interal artifactory (npm like).
The theme has custom styles, components and layouts as well as some assets like pictures stored in the themes `public` directory (for example `bg_gray.png`).
So far so good: I am able to build and deploy my theme as an NPM package in my artifactory.
I am also able to pull the theme into my slides repo and use it while running `npm run dev` (`slidev --open`) (so slidev in dev mode/watch).
As soon as I want to build the slidedeck (`slidev build`) for deployment, I receive the following error:

```
vite v4.5.0 building for production...
transforming (33) node_modules/@slidev/client/internals/Print.vue
node_modules/@my-npm-org/slidev-theme-my-theme/public/bg_gray.png referenced in /Users/user1/slides/node_modules/@my-npm-org/slidev-theme-my-theme/styles/layout.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

node_modules/@my-npm-org/slidev-theme-my-theme/public/bg.png referenced in /Users/user1/slides/node_modules/@my-npm-org/slidev-theme-my-theme/styles/layout.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

node_modules/@my-npm-org/slidev-theme-my-theme/public/db_logo.png referenced in /Users/user1/slides/node_modules/@my-npm-org/slidev-theme-my-theme/styles/layout.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 97 modules transformed.
✓ built in 700ms
[vite]: Rollup failed to resolve import "alt1.png" from "/@slidev/slides/24.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "alt1.png" from "/@slidev/slides/24.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/user1/slides/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///Users/user1/slides/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///Users/user1/slides/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///Users/user1/slides/node_modules/rollup/dist/es/shared/node-entry.js:24194:13
    at Object.logger [as onLog] (file:///Users/user1/slides/node_modules/rollup/dist/es/shared/node-entry.js:25867:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/user1/slides/node_modules/rollup/dist/es/shared/node-entry.js:24780:26)
    at file:///Users/user1/slides/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
```

The themes repo has no special configuration for vite and as written above, in dev mode, everything works (including referenced images from the `public` dir of the theme).
But: to be able to reference Images in CSS in the Themes repo as well as the consuming repo, I had to define a small CSS trick in the themes CSS:

```css
background-image: url("node_modules/@my-npm-org/slidev-theme-my-theme/public/bg_gray.png"), url("/bg_gray.svg")
```

This was needed, so the consuming repo is satisfied with the first part, the themes repo uses the local reference.

I Assume this way to do it is not the best / the wrong one. Can you help me solve it?

**To Reproduce**
1. Create a theme with referenced assets
2. Deploy the theme as NPM package
3. Use the theme
4. Run: `slidev build`

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Slidev version: 0.44.0

**Comment by d-koppenhagen** [comment]
Okay, I managed to fix it. There were two problems:
I replaced my assets in the theme package from `public` to `assets` and needed to adjust the paths (using a relative path):

### problem in theme

```diff
-background-image: url("node_modules/@my-npm-org/slidev-theme-my-theme/public/bg_gray.png"), url("/bg_gray.svg")
+background-image: url("../assets/bg_gray.svg")
```

### problem in slide repo

In the slide repo, the build was not successfull since I forgot the leading slashes (`/`):

```diff
-<img src="my-image.jpg">
+<img src="/my-image.jpg">
```

Probably this helps others running into the same issues :)
