### ISSUE TITLE
Failed to resolve import "vite-plugin-vue-server-ref/client" when opening the browser

### ISSUE THREAD

**Issue by mjblackhorse** [slidevjs/slidev#1221]
**Describe the bug**
I install slidev on my MacBook (macOS 14.0) with following script:

```
sudo npm I -g @slidev/cli
```

It can be run. However, when I try to open the browser, it does not work correctly. I find following error information:

```
14:51:05 [vite] Internal server error: Failed to resolve import "vite-plugin-vue-server-ref/client" from "../../../../../../@server-reactive/drawings?diff". Does the file exist?
  Plugin: vite:import-analysis
  File: /@server-reactive/drawings?diff:3:84
  1  |  
  2  |  import { reactive, watch } from "vue"
  3  |  import { randId, stringify, parse, define, apply, reactiveSet, clone, diff } from "vite-plugin-vue-server-ref/client"
     |                                                                                     ^
  4  |  const data = reactive({})
  5  |  let onSet = []
      at formatError (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:63408:46)
      at TransformContext.error (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:63402:19)
      at normalizeUrl (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:61677:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:61831:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:61752:13)
      at async Object.transform (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:63703:30)
      at async loadAndTransform (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:49384:29)
      at async viteTransformMiddleware (file:///usr/local/lib/node_modules/@slidev/cli/node_modules/vite/dist/node/chunks/dep-Pluk1iaB.js:58985:32)
14:51:05 [vite] Pre-transform error: Failed to resolve import "vite-plugin-vue-server-ref/client" from "../../../../../../@server-reactive/drawings?diff". Does the file exist?
14:51:05 [vite] Pre-transform error: Failed to resolve import "vite-plugin-vue-server-ref/client" from "../../../../../../@server-reactive/nav". Does the file exist?

```

**To Reproduce**
1. Go to the directory containing my markdown file
2. run 'sudo npc slides myfile.md'
3. Type 'o' to open the browser
4. See the error

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser: Safari
 - Slidev version: 0.46.0

**Comment by KermanX** [comment]
It seems that this has been fixed via https://github.com/antfu/vite-plugin-vue-server-ref/commit/adb925642e8ee989e55276e8ff16394405dc359a.
