### ISSUE TITLE
Unable to create default slides file

### ISSUE THREAD

**Issue by mikelorant** [slidevjs/slidev#1232]
**Describe the bug**
When attempting to start Slidev with no slides, default slides cannot be created.

**To Reproduce**
1. `rm slides.md`
2. `npx slidev`
3. You will then be prompted:
```
Entry file "slides.md" does not exist, do you want to create it?
```
Answering `yes` will cause Slidev to quit with the following error:
```
ReferenceError: __dirname is not defined
    at Object.handler (file:///slides/node_modules/@slidev/cli/dist/cli.mjs:104:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
```

A very easy way to reproduce this issue is via the official Docker container:

```
❯ docker run -it --rm --entrypoint=sh tangramor/slidev
/slidev # npm install @slidev/cli @slidev/theme-default @slidev/theme-seriph
npm WARN deprecated @types/lz-string@1.5.0: This is a stub types definition. lz-string provides its own type definitions, so you do not need this installed.

added 631 packages in 2m

181 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.2.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.5
npm notice Run npm install -g npm@10.2.5 to update!
npm notice
/slidev # npx slidev
✔ Entry file "slides.md" does not exist, do you want to create it? … yes
ReferenceError: __dirname is not defined
    at Object.handler (file:///slidev/node_modules/@slidev/cli/dist/cli.mjs:104:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**NodeJS versions**
I have tried multiple NodeJS versions ranging from `18` to `21` which have had no impact.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Slidev version: 0.46.1
 - NodeJS version: 20.10.0

**Comment by Wiederholung** [comment]
I also encountered the same problem.

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Browser: 120.0.2210.144 (official version) (64-bit)
- Slidev version: 0.46.2
- NodeJS version: 20.8.1

**Comment by mikelorant** [comment]
@antfu This issue is not resolved however the error has changed:

```
✔ Entry file "slides.md" does not exist, do you want to create it? … yes
node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /....../slides/slidev/node_modules/twoslash-vue/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.6.1
error Command failed with exit code 1.
```
