### ISSUE TITLE
Can't Load custom theme.json with Shikiji

### ISSUE THREAD

**Issue by alvarosabu** [slidevjs/slidev#1258]
**Describe the bug**
Hi, when I try to load my custom `theme.json` that I used for shiki before:

```ts
import { defineShikijiSetup } from '@slidev/types'

const myTheme = JSON.parse(fs.readFileSync('setup/theme/penguin-theme.json', 'utf8'))

export default defineShikijiSetup(() => ({
  theme: myTheme,
}))
```

It throws an error:

```bash
file:///Users/alvarosabu/Projects/alvarosabu/talks/slidev-theme-penguin/node_modules/.pnpm/shikiji-core@0.9.19/node_modules/shikiji-core/dist/index.mjs:5030
                    throw new Error(`[shikiji] Theme \`${theme}\` is not built-in.`);
                          ^

Error: [shikiji] Theme `theme-penguin` is not built-in.
    at resolveTheme (file:///Users/alvarosabu/Projects/alvarosabu/talks/slidev-theme-penguin/node_modules/.pnpm/shikiji-core@0.9.19/node_modules/shikiji-core/dist/index.mjs:5030:27)
    at file:///Users/alvarosabu/Projects/alvarosabu/talks/slidev-theme-penguin/node_modules/.pnpm/shikiji-core@0.9.19/node_modules/shikiji-core/dist/index.mjs:5035:57
    at Array.map (<anonymous>)
    at getHighlighter (file:///Users/alvarosabu/Projects/alvarosabu/talks/slidev-theme-penguin/node_modules/.pnpm/shikiji-core@0.9.19/node_modules/shikiji-core/dist/index.mjs:5035:48)
```

Is it currently possible to load custom themes? Thanks
    
  

**To Reproduce**
1. `npm run dev`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: None
 - Slidev version: `v0.46.3`

**Comment by antfu** [comment]
Can you share a minimal repro? Thanks

**Comment by alvarosabu** [comment]
Yes sorry, here is it https://stackblitz.com/edit/vitejs-vite-fm6jjj?file=setup%2Fshikiji.ts

**Comment by antfu** [comment]
Before the release, here is that workaround:

```ts
import fs from 'node:fs';

/* ./setup/shiki.ts */

import { defineShikijiSetup } from '@slidev/types';

const myTheme = JSON.parse(
  fs.readFileSync('setup/theme/penguin-theme.json', 'utf8')
);

export default defineShikijiSetup(() => ({
  themes: { default: myTheme },
  defaultColor: 'default',
}));
```

**Comment by alvarosabu** [comment]
Thanks @antfu that was extremely quick 🙏🏻
