### ISSUE TITLE
Manually installed slidev via pnpm fails with an error when executing `pnpx slidev`

### ISSUE THREAD

**Issue by shoichiaizawa** [slidevjs/slidev#131]
Following the [docs](https://sli.dev/guide/install.html#install-manually), I installed `slidev` via `pnpm` but executing `pnpx slidev` ends up with an error.

Here is what I did:

```sh
❯❯ node -v
v14.17.0

❯❯ pnpm -v
6.3.0

❯❯ pnpm install @slidev/cli @slidev/theme-default
 WARN  @slidev/cli: vite-plugin-icons@0.5.1 requires a peer of vue-template-compiler@^2.6.12 but none was installed.
 WARN  @slidev/theme-default@0.7.3 requires a peer of @slidev/client@^0.6.7 but none was installed.
Packages: +277
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/sho/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 277, reused 277, downloaded 0, added 277, done
node_modules/.pnpm/esbuild@0.11.23/node_modules/esbuild: Running postinstall script, done in 284ms
node_modules/.pnpm/vue-demi@0.9.0_vue@3.0.11/node_modules/vue-demi: Running postinstall script, done in 165ms
node_modules/.pnpm/vue-demi@0.7.4_vue@3.0.11/node_modules/vue-demi: Running postinstall script, done in 148ms

dependencies:
+ @slidev/cli 0.10.2
+ @slidev/theme-default 0.7.3

❯❯ touch slides.md

❯❯ echo 'shamefully-flatten=true' >> .npmrc
```

And run the `pnpx slidev` command:

```sh
❯❯ pnpx slidev
(node:85702) UnhandledPromiseRejectionWarning: Error: Failed to resolve force included dependency: @antfu/utils
    at optimizeDeps (/Users/sho/slidev-pnpm/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:64756:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOptimize (/Users/sho/slidev-pnpm/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68555:48)
    at async Server.httpServer.listen (/Users/sho/slidev-pnpm/node_modules/.pnpm/vite@2.3.3/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68569:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:85702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:85702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/1571648/118740941-14441000-b888-11eb-97d9-3029018a856a.png)

---

NOTE: I always run `npm init slidev` to scaffold my slides. But this time, I did it manually just because I wanted to try it out.

**Comment by Ahacad** [comment]
This problem happens on my machine, too. I think it's because the different way `pnpm` and `npm` functions, if you use `npm` from the [website doc](https://sli.dev/guide/install.html#starter-template) things work out fine.

```
$ npm install @slidev/cli @slidev/theme-default
$ touch slides.md
$ npx slidev
```

**Comment by antfu** [comment]
https://sli.dev/guide/install.html#install-manually

Have you turned `shamefully-hoist` on?

**Comment by antfu** [comment]
Close due to inactive
