### ISSUE TITLE
`slidev build --out ./somewhere/` -> Monaco broken

### ISSUE THREAD

**Issue by pinage404** [slidevjs/slidev#1329]
**Describe the bug**
With slidev `0.47` Monaco was broken (using `slidev` nor `slidev build`) https://github.com/slidevjs/slidev/issues/1278

With slidev `^0.48.0-beta.6`
* when using `slidev` or `slidev build`, Monaco has been fixed by https://github.com/slidevjs/slidev/pull/1308 
* when using `slidev build --out ./somewhere/`, the build fail with an infinite `iframe` folder generation https://gitlab.com/pinage404/slidev_with_monaco/-/jobs/6244339929#L66

I updated the repository to isolate and reproduce the problem :
https://gitlab.com/pinage404/slidev_with_monaco/-/blob/main/slides.md

**To Reproduce**
1. Install slidev
2. Use a Monaco code block in your slide
3. In front matter, [enable Monaco even in the exported SPA](https://sli.dev/custom/config-monaco#exporting) :  `monaco: true`
4. Build to SPA : `slidev build --out ./somewhere/`
5. The build fail with

<details>

<summary>long error message</summary>

```txt
Error: ENAMETOOLONG: name too long, copyfile '/home/pinage404/Project/slidev_with_monaco/public/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/assets/logo-title-horizontal-XSaaVPPu.png' -> '/home/pinage404/Project/slidev_with_monaco/somewhere/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/assets/logo-title-horizontal-XSaaVPPu.png'
    at Object.copyFileSync (node:fs:3029:11)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12458:18)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13)
    at copyDir (file:///home/pinage404/Project/slidev_with_monaco/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:12455:13) {
  errno: -36,
  code: 'ENAMETOOLONG',
  syscall: 'copyfile',
  path: '/home/pinage404/Project/slidev_with_monaco/public/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/assets/logo-title-horizontal-XSaaVPPu.png',
  dest: '/home/pinage404/Project/slidev_with_monaco/somewhere/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/iframes/monaco/assets/logo-title-horizontal-XSaaVPPu.png'
}
```

</details> 

**Desktop (please complete the following information):**
 - OS: NixOS 23.11.20240209.20f65b8 (Tapir)
 - Browser: NA
 - Slidev version: 0.48.0-beta.6

**Comment by antfu** [comment]
@KermanX is working on a new approach of mounting Monaco directly without iframe, it should solve quite a lot issues around Monaco: https://github.com/slidevjs/slidev/pull/1330

Before that, you might want to downgrade Slidev a bit.

**Comment by pinage404** [comment]
[It works](https://pinage404.gitlab.io/slidev_with_monaco/), thanks !
