### ISSUE TITLE
`generateError` on hot-load

### ISSUE THREAD

**Issue by aytey** [slidevjs/slidev#1467]
## Describe the bug

When I try to render:

```md
---
# Words

* More words

---

# Another slide
```

I get the following:

```
name of an alias node must contain at least one character (3:2)

 1 | # Words
 2 | 
 3 | * More words
------^
    at generateError (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:1273:10)
    at throwError (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:1277:9)
    at readAlias (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2441:5)
    at composeNode (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2540:20)
    at readBlockMapping (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2194:12)
    at composeNode (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2531:12)
    at readDocument (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2715:3)
    at loadDocuments (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2778:5)
    at Object.load$1 [as load] (file:///D:/DEV/honk/slidev/node_modules/js-yaml/dist/js-yaml.mjs:2804:19)
    at Module.load (file:///D:/DEV/honk/slidev/node_modules/@slidev/parser/dist/fs.mjs:39:20
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

## To Reproduce

```sh
mkdir honk
cd honk
npm init slidev@latest
# this launches `slidev --open`
# replace `slides.md` with the content given above
# let the browser automatically refresh
```

Note: if you manually refresh the page after it has hot-loaded, the bug goes away

## Desktop (please complete the following information)

- OS: Windows 11H23 (22631.3155)
- Browser: Chrome Version 123.0.6312.58 (Official Build) (64-bit)
- Slidev version: v0.48.7

**Comment by aytey** [comment]
Sure, but this is only a bug on hot-reload, right?

Weirdly, if you fully refresh the page, it does render correctly (which I didn't expect; I expected it always to broken or never to broken, not "half and half").
