### ISSUE TITLE
Some code snippet can make slidev crash

### ISSUE THREAD

**Issue by Toilal** [slidevjs/slidev#151]
I try to embed this code in a slide, but it seems to make slidev crash.

```ini
###> nelmio/cors-bundle ###
CORS_ALLOW_ORIGIN=^https?://(?:api[\.-])?{{core.domain.sub}}\.{{core.domain.ext}}$
###< nelmio/cors-bundle ###
```

To reproduce, run `npm init slidev` and add this snippet surrounded with usual three backticks and langage into first slide.

**Comment by Toilal** [comment]
Please note that removing `^https?://(?:api[\.-])?{{core.domain.sub}}\.{{core.domain.ext}}$` part from the snippet make things work, so it seems there's something in the regex that triggers the crash.

**Comment by Toilal** [comment]
I have narrowed things down, and it seems to crash because of the mustache `{{...}}` pattern if it occurs more that one time.

_**Pass**_
```text
{{a}}
```

_**Pass**_
```text
{{b}}
```

_**Fail**_
```text
{{a}} {{b}}
```

**Comment by Toilal** [comment]
And the stacktrace, it seems to crash in vite vue plugin.

```
[vite] Internal server error: Cannot read property 'line' of undefined
  Plugin: vite:vue
  File: /@slidev/slides/10.md
      at createRollupError (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\@vitejs\plugin-vue\dist\index.js:4092:29)
      at C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\@vitejs\plugin-vue\dist\index.js:4346:51
      at Array.forEach (<anonymous>)
      at transformMain (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\@vitejs\plugin-vue\dist\index.js:4346:12)
      at TransformContext.transform (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\@vitejs\plugin-vue\dist\index.js:4665:16)
      at Object.transform (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\vite\dist\node\chunks\dep-e9a16784.js:44268:53)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async transformRequest (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\vite\dist\node\chunks\dep-e9a16784.js:58540:29)
      at async viteTransformMiddleware (C:\Users\FRUP67305\projects\MENJ-Accompagnement-Dev-Workflow\node_modules\vite\dist\node\chunks\dep-e9a16784.js:58678:32)
```

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/119158189-8be08d80-ba88-11eb-9a94-c4a0623f79e0.png)
Works fine for me, have you upgraded to the latest version?

**Comment by Toilal** [comment]
Slidev  v0.12.1

**Comment by Toilal** [comment]
Important stuff, and i'm sorry about that, I run on Windows NodeJS 14.17.0. I'll give a try on my linux computer right now.

**Comment by antfu** [comment]
Ah, why are you using `###` instead of ```? If they are not inside of code blocks, mustache are treated as Vue template interpretations.

**Comment by Toilal** [comment]
```###``` Are comments inside the snippet I want to display in slide. But anyway, I can reproduce the error without those symbols, on Linux Ubuntu too.

Please clone this minimal reproduction repository : https://github.com/Toilal/slide-issue-repro

``npm install & npm run dev``, you should reproduce the crash.

**Comment by Ahacad** [comment]
I can reproduce this error on my machine:

```
[plugin:vite:vue] ENOENT: no such file or directory, open '/@slidev/slides/1.md'
```

strange message, not sure where is the problem yet.
