### ISSUE TITLE
Cannot export mermaid figures into pdf

### ISSUE THREAD

**Issue by apraga** [slidevjs/slidev#1528]
**Describe the bug**
Export to PDF fails for mermaid figures.

**To Reproduce**

1. Minimal working example from the documentation : `test.md`
```
---
theme: default
title: Title 
---

# Test

\`\`\`mermaid {theme: 'neutral', scale: 0.8}
graph TD
B[Text] --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
\`\`\`
```
2. Export to PDF 

 `npx slidev export  test.md`

Errors are 
```
  ●■▲
  Slidev  v0.48.9

  theme       @slidev/theme-default
  css engine  unocss
  entry       /home/alex/notes/slides/test.md
  ● rendering...locator.evaluate: Error: strict mode violation: locator('body').locator('#mermaid-rendering-container
    1) <div id="mermaid-rendering-container"></div> aka locator('#mermaid-rendering-container').first()
    2) <div id="mermaid-rendering-container"></div> aka locator('#mermaid-rendering-container').nth(1)
    3) <div id="mermaid-rendering-container"></div> aka locator('#mermaid-rendering-container').nth(2)
    4) <div id="mermaid-rendering-container"></div> aka locator('#mermaid-rendering-container').nth(3)

Call log:
  - waiting for locator('body').locator('#mermaid-rendering-container')

    at go (/home/alex/notes/slides/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:198:25)
    at async genPagePdfOnePiece (/home/alex/notes/slides/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:278:5)
    at async exportSlides (/home/alex/notes/slides/node_modules/@slidev/cli/dist/export-H5Y2LN6J.mjs:383:5)
    at async Object.handler (/home/alex/notes/slides/node_modules/@slidev/cli/dist/cli.mjs:422:22)

```

**Desktop (please complete the following information):**
- OS: gentoo
- Browser: firefox
- Slidev version: 0.48.9

I've updated all dependencies. Any help appreciated, thanks !

**Comment by apraga** [comment]
The issue was actually a `index.html` laying around in the folder. Removing it solved it. Sorry for the noise...
