### ISSUE TITLE
Slidev won't start - TypeError: returns.toReversed is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by robert-niestroj** [slidevjs/slidev#1779]
**Describe the bug**

With a fresh sli.dev 0.49.21 i get the following error. 

PS C:\slidev\p1> npm exec slidev -- --port 3030 "slides.md"
file:///C:/slidev/p1/node_modules/@slidev/cli/dist/chunk-I465XJNL.js:8564
  for (const r of returns.toReversed()) {
                          ^

TypeError: returns.toReversed is not a function or its return value is not iterable
    at setupTransformers (file:///C:/slidev/p1/node_modules/@slidev/cli/dist/chunk-I465XJNL.js:8564:27)
    at async getMarkdownTransformers (file:///C:/slidev/p1/node_modules/@slidev/cli/dist/chunk-I465XJNL.js:8895:18)
    at async createMarkdownPlugin (file:///C:/slidev/p1/node_modules/@slidev/cli/dist/chunk-I465XJNL.js:9303:24)   
    at async Promise.all (index 1)

Node.js v18.13.0 / Win10

**Environment**

- Slidev version: 0.49.21
- Browser: Firefox
- OS: Windows 10

**Comment by KermanX** [comment]
Pushed a fix (cd7f926e7f3650b76bcaa695b14e4699549c1ab4). Sorry for the inconvenience. ATM, you can upgrade Node to 20 or downgrade Slidev to 0.49.17.
