### ISSUE TITLE
--out to dist/dir/ raises and error

### ISSUE THREAD

**Issue by varadinov** [slidevjs/slidev#1901]
**Describe the bug**
When run slidev build with --out dist/dirXXX raises an error
```
npm run build "file.md" --out "dist/XXX"
````

```
✓ built in 7.03s
Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:448:20)
    at Module.load (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/parser/dist/fs.mjs:28:49)
    at resolveOptions (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/cli/dist/chunk-YP37OZJY.js:1105:31)
    at async Object.handler (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/cli/dist/cli.js:339:23) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

**Minimal reproduction**

1. Create new slidev project
2. Create multiple .md files
3. Run build for specific .md file - npm run build "file.md" --out "dist/dir"
**Note:**
4. See the error
```
✓ built in 7.03s
Error: EISDIR: illegal operation on a directory, read
    at Object.readFileSync (node:fs:448:20)
    at Module.load (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/parser/dist/fs.mjs:28:49)
    at resolveOptions (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/cli/dist/chunk-YP37OZJY.js:1105:31)
    at async Object.handler (file:///home/borislav/dev/devops_101_course/site/course_modules/node_modules/@slidev/cli/dist/cli.js:339:23) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```
5. If I'm not using the --out parameter the build passes without errors
6. Even with the error the presentation works fine

**Environment**

- Slidev version:  ^0.49.29
- Browser: N/A
- OS: Ubuntu 24.04
- 
Slidev is used locally

**Comment by KermanX** [comment]
NPM requires an extra `--` before options that should be passed to the actual command. Using `npm run build "file.md" -- --out "dist/XXX"` or `pnpm run build "file.md" --out "dist/XXX"` may help

**Comment by varadinov** [comment]
Thanks!
It works like a charm!
