### ISSUE TITLE
Unable to build with Monaco Editor enabled

### ISSUE THREAD

**Issue by ghaiklor** [slidevjs/slidev#194]
**Describe the bug**
When running `slidev build` for the slides where `monaco: true` entry present, it fails on bundling.

```


  ●■▲
  Slidev  v0.15.0

  theme   @slidev/theme-default
  entry   /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/src/2021-06-03-wix-type-challenges.md


vite v2.3.4 building for production...
✓ 194 modules transformed.
dist/assets/f16965043a9db39096ecfb63f3f4ae39.a02f38e2.png   59.08kb
dist/assets/logo-title-horizontal.96c3c915.png              119.68kb
dist/assets/logo.b72bde5d.png                               92.11kb
dist/index.html                                             0.69kb
dist/assets/FileSaver.min.29c06842.js                       2.72kb / brotli: 1.09kb
dist/assets/index.036e2e5d.css                              37.97kb / brotli: 6.88kb
dist/assets/index.87c5a653.js                               63.73kb / brotli: 20.08kb
dist/assets/motion.b7ddb768.js                              94.34kb / brotli: 30.20kb
  building for Monaco...

vite v2.3.4 building for production...
✓ 23 modules transformed.
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/prettier/esm/parser-html.mjs:24:920
```

**To Reproduce**
1. Add an entry `monaco: true` to the Front Matter
2. Add snippets with `{monaco}` section
3. Run `slidev build` for this slides.md

**Comment by ghaiklor** [comment]
Thanks! I can confirm that commit acd0700b76ef8e5065550fe2375d705c37772138 fixed the build ❤️

**Comment by Cathon** [comment]
**Describe the bug**
I met the same problem above in the version 0.22.7
enviroment:
- Windows 10
- node 14.17.4
- npm 6.14.14

```
> npx slidev build

  ●■▲
  Slidev  v0.22.7

  theme   slidev-theme-aliyun
  entry   D:\Projects\linuxshell\slidev\slides.md

vite v2.4.4 building for production...
✓ 228 modules transformed.
dist/assets/8b9eb19119592679c97707c257d88026.a02f38e2.png   59.08kb
dist/assets/logo-title-horizontal.96c3c915.png              119.68kb
dist/assets/logo.b72bde5d.png                               92.11kb
...
dist/assets/bg2.e66a9242.png                                971.41kb
dist/assets/250539c1f1bdac4cc5d0625f5b130e30.67a454ee.png   1820.87kb
dist/index.html                                             0.66kb
dist/assets/index.6429bbec.js                               0.03kb / brotli: 0.03kb
dist/assets/FileSaver.min.29c06842.js                       2.72kb / brotli: 1.09kb
dist/assets/vendor.608f7d8a.css                             68.36kb / brotli: 13.68kb
dist/assets/vendor.0d498298.js                              196.86kb / brotli: 58.19kb
  building for Monaco...

vite v2.4.4 building for production...
transforming (1) ..\..\..\..\monaco-editor\esm\vs\language\typescript\ts.worker.jsThe 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
transforming (3) ..\..\..\..\monaco-editor\esm\vs\language\typescript\tsWorker.jsThe 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
✓ 18 modules transformed.
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-html.mjs:24:920
22:  * found in the LICENSE file at https://angular.io/license
23:  */
24: const a=/-+([a-z0-9])/g;var u=function(e){return e.replace(a,((...e)=>e[1].toUpperCase()))};var c=function(e,t){return p(e,":",t)};var l=function(e,t){return p(e,".",t)};function p(e,t,r){const n=e.indexOf(t);return-1==n?r:[e.slice(0,n).trim(),e.slice(n+1).trim()]}function D(e,t,r){return Array.isArray(e)?t.visitArray(e,r):"object"==typeof(n=e)&&null!==n&&Object.getPrototypeOf(n)===b?t.visitStringMap(e,r):null==e||"string"==typeof e||"number"==typeof e||"boolean"==typeof e?t.visitPrimitive(e,r):t.visitOther(e,r);var n}var h=D;var d=function(e){return null!=e};var f=function(e){return void 0===e?null:e};var m=class{visitArray(e,t){return e.map((e=>D(e,this,t)))}visitStringMap(e,t){const r={};return Object.keys(e).forEach((n=>{r[n]=D(e[n],this,t)})),r}visitPrimitive(e,t){return e}visitOther(e,t){return e}},g={assertSync:e=>{if(N(e))throw new Error("Illegal state: value cannot be a promise");return e},then:(e,t)=>N(e)?e.then(t):t(e),all:e=>e.some(N)?Promise.all(e):e};var E=function(e){throw new Error(`Internal Error: ${e}`)};var C=function(e,t){const r=Error(e);return r[T]=!0,t&&(r[y]=t),r};const T="ngSyntaxError",y="ngParseErrors";var S=function(e){return e[T]};var _=function(e){return e[y]||[]};var v=function(e){return e.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")};const b=Object.getPrototypeOf({});var F=function(e){let t="";for(let r=0;r<e.length;r++){let n=e.charCodeAt(r);if(n>=55296&&n<=56319&&e.length>r+1){const t=e.charCodeAt(r+1);t>=56320&&t<=57343&&(r++,n=(n-55296<<10)+t-56320+65536)}n<=127?t+=String.fromCharCode(n):n<=2047?t+=String.fromCharCode(n>>6&31|192,63&n|128):n<=65535?t+=String.fromCharCode(n>>12|224,n>>6&63|128,63&n|128):n<=2097151&&(t+=String.fromCharCode(n>>18&7|240,n>>12&63|128,n>>6&63|128,63&n|128))}return t};var A=function e(t){if("string"==typeof t)return t;if(t instanceof Array)return"["+t.map(e).join(", ")+"]";if(null==t)return""+t;if(t.overriddenName)return`${t.overriddenName}`;if(t.name)return`${t.name}`;if(!t.toString)return"object";const r=t.toString();if(null==r)return""+r;const n=r.indexOf("\n");return-1===n?r:r.substring(0,n)};var w=function(e){return"function"==typeof e&&e.hasOwnProperty("__forward_ref__")?e():e};function N(e){return!!e&&"function"==typeof e.then}var k=N;var O=class{constructor(e){this.full=e;const t=e.split(".");this.major=t[0],this.minor=t[1],this.patch=t.slice(2).join(".")}};const x="undefined"!=typeof window&&window,I="undefined"!=typeof self&&"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope&&self;var P=void 0!==e&&e||x||I,R=Object.defineProperty({dashCaseToCamelCase:u,splitAtColon:c,splitAtPeriod:l,visitValue:h,isDefined:d,noUndefined:f,ValueTransformer:m,SyncAsync:g,error:E,syntaxError:C,isSyntaxError:S,getParseErrors:_,escapeRegExp:v,utf8Encode:F,stringify:A,resolveForwardRef:w,isPromise:k,Version:O,global:P},"__esModule",{value:!0}),L=t((function(e,t){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^
25: /**
26:    * @license
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:151:30)
    at Module.error (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:10044:16)
    at Module.tryParse (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:10447:25)
    at Module.setSource (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:10350:24)
    at ModuleLoader.addModuleSource (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:19706:20)
    at async ModuleLoader.fetchModule (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:19762:9)
    at async D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:19737:48
    at async Promise.all (index 2)
    at async ModuleLoader.fetchDynamicDependencies (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:19727:30)
    at async Promise.all (index 1) {
  code: 'PARSE_ERROR',
  parserError: SyntaxError: Unexpected token (24:920)
      at Parser.pp$4.raise (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16954:13)
      at Parser.pp.unexpected (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:14462:8)
      at Parser.pp.expect (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:14456:26)
      at Parser.pp$3.parseObj (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16568:12)
      at Parser.pp$3.parseExprAtom (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16307:17)
      at Parser.pp$3.parseExprSubscripts (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16126:19)
      at Parser.pp$3.parseMaybeUnary (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16092:17)
      at Parser.pp$3.parseExprOps (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16025:19)
      at Parser.pp$3.parseMaybeConditional (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:16008:19)
      at Parser.pp$3.parseMaybeAssign (D:\Projects\linuxshell\slidev\node_modules\rollup\dist\shared\rollup.js:15976:19) {
    pos: 3352,
    loc: Position { line: 24, column: 920 },
    raisedAt: 3354
  },
  id: 'D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-html.mjs',
  pos: 3352,
  loc: {
    column: 920,
    file: 'D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-html.mjs',
    line: 24
  },
  frame: '22:  * found in the LICENSE file at https://angular.io/license\n' +
    '23:  */\n' +
    '24: const a=/-+([a-z0-9])/g;var u=function(e){return e.replace(a,((...e)=>e[1].toUpperCase()))};var c=function(e,t){return p(e,":",t)};var l=function(e,t){return p(e,".",t)};function p(e,t,r){const n=e.indexOf(t);return-1==n?r:[e.slice(0,n).trim(),e.slice(n+1).trim()]}function D(e,t,r){return Array.isArray(e)?t.visitArray(e,r):"object"==typeof(n=e)&&null!==n&&Object.getPrototypeOf(n)===b?t.visitStringMap(e,r):null==e||"string"==typeof e||"number"==typeof e||"boolean"==typeof e?t.visitPrimitive(e,r):t.visitOther(e,r);var n}var h=D;var d=function(e){return null!=e};var f=function(e){return void 0===e?null:e};var m=class{visitArray(e,t){return e.map((e=>D(e,this,t)))}visitStringMap(e,t){const r={};return Object.keys(e).forEach((n=>{r[n]=D(e[n],this,t)})),r}visitPrimitive(e,t){return e}visitOther(e,t){return e}},g={assertSync:e=>{if(N(e))throw new Error("Illegal state: value cannot be a promise");return e},then:(e,t)=>N(e)?e.then(t):t(e),all:e=>e.some(N)?Promise.all(e):e};var E=function(e){throw new Error(`Internal Error: ${e}`)};var C=function(e,t){const r=Error(e);return r[T]=!0,t&&(r[y]=t),r};const T="ngSyntaxError",y="ngParseErrors";var S=function(e){return e[T]};var _=function(e){return e[y]||[]};var v=function(e){return e.replace(/([.*+?^=!:${}()|[\\]\\/\\\\])/g,"\\\\$1")};const b=Object.getPrototypeOf({});var F=function(e){let t="";for(let r=0;r<e.length;r++){let n=e.charCodeAt(r);if(n>=55296&&n<=56319&&e.length>r+1){const t=e.charCodeAt(r+1);t>=56320&&t<=57343&&(r++,n=(n-55296<<10)+t-56320+65536)}n<=127?t+=String.fromCharCode(n):n<=2047?t+=String.fromCharCode(n>>6&31|192,63&n|128):n<=65535?t+=String.fromCharCode(n>>12|224,n>>6&63|128,63&n|128):n<=2097151&&(t+=String.fromCharCode(n>>18&7|240,n>>12&63|128,n>>6&63|128,63&n|128))}return t};var A=function e(t){if("string"==typeof t)return t;if(t instanceof Array)return"["+t.map(e).join(", ")+"]";if(null==t)return""+t;if(t.overriddenName)return`${t.overriddenName}`;if(t.name)return`${t.name}`;if(!t.toString)return"object";const r=t.toString();if(null==r)return""+r;const n=r.indexOf("\\n");return-1===n?r:r.substring(0,n)};var w=function(e){return"function"==typeof e&&e.hasOwnProperty("__forward_ref__")?e():e};function N(e){return!!e&&"function"==typeof e.then}var k=N;var O=class{constructor(e){this.full=e;const t=e.split(".");this.major=t[0],this.minor=t[1],this.patch=t.slice(2).join(".")}};const x="undefined"!=typeof window&&window,I="undefined"!=typeof self&&"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope&&self;var P=void 0!==e&&e||x||I,R=Object.defineProperty({dashCaseToCamelCase:u,splitAtColon:c,splitAtPeriod:l,visitValue:h,isDefined:d,noUndefined:f,ValueTransformer:m,SyncAsync:g,error:E,syntaxError:C,isSyntaxError:S,getParseErrors:_,escapeRegExp:v,utf8Encode:F,stringify:A,resolveForwardRef:w,isPromise:k,Version:O,global:P},"__esModule",{value:!0}),L=t((function(e,t){\n' +
    '                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^\n' +
    '25: /**\n' +
    '26:    * @license',
  watchFiles: [
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/iframes/monaco/index.html',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/iframes/monaco/index.ts',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/iframes/monaco/index.css',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/setup/prettier.ts',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/setup/monaco.ts',
    '/@slidev/styles',
    '/@slidev/monaco-types',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/styles/vars.css',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/styles/index.css',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/styles/code.css',
    'D:/Projects/linuxshell/slidev/node_modules/slidev-theme-aliyun/styles/index.ts',
    'D:/Projects/linuxshell/slidev/node_modules/katex/dist/katex.min.css',
    'D:/Projects/linuxshell/slidev/node_modules/prettier/standalone.js',
    'D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-babel.mjs',
    'D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-typescript.mjs',
    'D:/Projects/linuxshell/slidev/node_modules/prettier/esm/parser-html.mjs',
    'D:/Projects/linuxshell/slidev/node_modules/slidev-theme-aliyun/styles/layout.css',
    'D:/Projects/linuxshell/slidev/node_modules/slidev-theme-aliyun/styles/code.css',
    'D:/Projects/linuxshell/slidev/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/editor/editor.main.js',
    'D:/Projects/linuxshell/slidev/node_modules/@antfu/utils/dist/index.mjs',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/editor/editor.worker.js?worker',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/json/json.worker.js?worker',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/css/css.worker.js?worker',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/html/html.worker.js?worker',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js?worker',
    'D:/Projects/linuxshell/slidev/node_modules/@slidev/client/styles/layouts-base.css',
    'D:/Projects/linuxshell/slidev/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/typescript/monaco.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/css/monaco.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/json/monaco.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/html/monaco.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/monaco.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/editor/edcore.main.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/editor/editor.api.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/css/fillers/monaco-editor-core.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/css/cssMode.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/typescript/lib/typescriptServicesMetadata.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/typescript/fillers/monaco-editor-core.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/typescript/tsMode.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/json/fillers/monaco-editor-core.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/json/jsonMode.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/html/fillers/monaco-editor-core.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/language/html/htmlMode.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/abap/abap.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/apex/apex.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/azcli/azcli.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/bat/bat.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/bicep/bicep.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/cameligo/cameligo.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/clojure/clojure.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/coffee/coffee.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/cpp/cpp.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/csharp/csharp.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/csp/csp.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/css/css.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/dart/dart.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/dockerfile/dockerfile.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/ecl/ecl.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/elixir/elixir.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/fsharp/fsharp.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/go/go.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/graphql/graphql.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/handlebars/handlebars.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/hcl/hcl.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/html/html.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/ini/ini.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/java/java.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/julia/julia.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/kotlin/kotlin.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/less/less.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/lexon/lexon.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/lua/lua.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/liquid/liquid.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/m3/m3.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/markdown/markdown.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/mips/mips.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/msdax/msdax.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/mysql/mysql.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/objective-c/objective-c.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/pascal/pascal.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/pascaligo/pascaligo.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/perl/perl.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/pgsql/pgsql.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/php/php.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/postiats/postiats.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/powerquery/powerquery.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/powershell/powershell.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/pug/pug.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/python/python.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/qsharp/qsharp.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/r/r.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/razor/razor.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/redis/redis.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/redshift/redshift.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/restructuredtext/restructuredtext.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/ruby/ruby.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/rust/rust.contribution.js',
    'D:/Projects/linuxshell/slidev/node_modules/monaco-editor/esm/vs/basic-languages/sb/sb.contribution.js',
    ... 29 more items
  ]
}
```
