### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Build failed with 26 errors:

### ISSUE THREAD

**Issue by renxia** [slidevjs/slidev#212]
**Describe the bug**

按文档说明安装并试用了一下，在 windows 10 下没跑起来，报错如下：

```txt
> dep:codemirror_mode_xml_xml:1:23: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/codemirror@5.61.1/node_modules/codemirror/mode/xml/xml.js"
    1 │ export default require("./E:/lzwme/slidev/node_modules/.pnpm/codemirror@5.61.1/node_modules/codemirror/mode/xml/xml.js");
      ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > dep:mermaid_dist_mermaid_min:1:23: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/mermaid@8.5.0/node_modules/mermaid/dist/mermaid.min.js"
    1 │ export default require("./E:/lzwme/slidev/node_modules/.pnpm/mermaid@8.5.0/node_modules/mermaid/dist/mermaid.min.js");
      ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(node:165588) UnhandledPromiseRejectionWarning: Error: Build failed with 26 errors:
dep:@antfu_utils:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@antfu+utils@0.1.6/node_modules/@antfu/utils/dist/index.mjs"
dep:@slidev_parser:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@slidev+parser@0.16.1/node_modules/@slidev/parser/dist/index.mjs"
dep:@vueuse_head:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@vueuse+head@0.5.1_vue@3.0.11/node_modules/@vueuse/head/dist/index.mjs"
dep:@vueuse_motion:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@vueuse+motion@1.5.6_vue@3.0.11/node_modules/@vueuse/motion/dist/index.esm-bundler.js"
dep:codemirror:1:23: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/codemirror@5.61.1/node_modules/codemirror/lib/codemirror.js"
...
    at failureErrorWithLog (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1466:15)
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1148:28
    at runOnEndCallbacks (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:938:63)
    at buildResponseToResult (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1146:7)
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1253:14
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:165588) Error: Build failed with 26 errors:
dep:@antfu_utils:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@antfu+utils@0.1.6/node_modules/@antfu/utils/dist/index.mjs"
dep:@slidev_parser:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@slidev+parser@0.16.1/node_modules/@slidev/parser/dist/index.mjs"
dep:@vueuse_head:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@vueuse+head@0.5.1_vue@3.0.11/node_modules/@vueuse/head/dist/index.mjs"
dep:@vueuse_motion:2:14: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/@vueuse+motion@1.5.6_vue@3.0.11/node_modules/@vueuse/motion/dist/index.esm-bundler.js"
dep:codemirror:1:23: error: Could not resolve "./E:/lzwme/slidev/node_modules/.pnpm/codemirror@5.61.1/node_modules/codemirror/lib/codemirror.js"
...
    at failureErrorWithLog (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1466:15)
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1148:28
    at runOnEndCallbacks (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:938:63)
    at buildResponseToResult (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1146:7)
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:1253:14
    at e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (e:\lzwme\slidev\node_modules\.pnpm\esbuild@0.12.5\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
(node:165588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
```

**To Reproduce**

```bash
yarn create slidev
cd slidev
# 重试 install
pnpm install
npm run dev
```

只是简单的按如上步骤操作了一次，无法成功运行

**Desktop (please complete the following information):**
 - OS: windows 10
 -  nodejs: 14.17.0
 - Slidev version: 0.16.1

**Comment by antfu** [comment]
Just tried on Windows 10 and it works fine for me. Have you tried with `npm` or `yarn`?

**Comment by renxia** [comment]
> Just tried on Windows 10 and it works fine for me. Have you tried with `npm` or `yarn`?

找到原因了，是因为我这个 `coding` 目录是一个快捷方式引用路径，进去的是 D 盘中的文件夹，但文件实际在 E 盘。是 windows 上的符号引用存在的问题。
感谢回复！
