### ISSUE TITLE
Slidev doesn't run on M1 MacBook Pro

### ISSUE THREAD

**Issue by originalix** [slidevjs/slidev#240]
**Describe the bug**
```
➜  github yarn create slidev
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-slidev@0.20.0" with binaries:
      - create-slidev
[#######################################################################################################################################################################] 529/529
  ●■▲
  Slidev Creator  v0.20.0

✔ Project name: … slidev-demo
  Scaffolding project in slidev-demo ...
  Done.

✔ Install and start it now? … yes
✔ Choose the agent › yarn
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning @slidev/theme-default@0.19.1: The engine "slidev" appears to be invalid.
warning theme-vitesse@0.1.12: The engine "vscode" appears to be invalid.
warning @slidev/theme-seriph@0.19.1: The engine "slidev" appears to be invalid.
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 13.50s.
yarn run v1.22.10
$ slidev --open


#
# Fatal error in , line 0
# Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
#
#
#
#FailureMessage Object: 0x16b930b68
 1: 0x1045ca358 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 2: 0x10530c620 V8_Fatal(char const*, ...) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 3: 0x104c600b0 v8::internal::wasm::WasmCodeManager::Decommit(v8::base::AddressRegion) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 4: 0x104c63730 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 5: 0x104c72918 v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 6: 0x104c70620 v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 7: 0x104c71a94 v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 8: 0x104c71e44 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
 9: 0x1047fb870 v8::internal::StackGuard::HandleInterrupts() [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
10: 0x104b36d48 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
11: 0x104e2808c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
12: 0x104dc0e30 Builtins_InterpreterEntryTrampoline [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
13: 0x104dc0d94 Builtins_InterpreterEntryTrampoline [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
14: 0x104dc0d94 Builtins_InterpreterEntryTrampoline [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
15: 0x104db83c4 Builtins_ArgumentsAdaptorTrampoline [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
16: 0x104dc0d94 Builtins_InterpreterEntryTrampoline [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
17: 0x104ded194 Builtins_AsyncFunctionAwaitResolveClosure [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
18: 0x104e7431c Builtins_PromiseFulfillReactionJob [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
19: 0x104ddff08 Builtins_RunMicrotasks [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
20: 0x104dbe528 Builtins_JSRunMicrotasksEntry [/Users/Lix/.nvm/versions/node/v15.5.1/bin/node]
21: 0x158008000
error Command failed with signal "SIGTRAP".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed with exit code 1: yarn run dev
    at makeError (/Users/Lix/.config/yarn/global/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/Lix/.config/yarn/global/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async init (/Users/Lix/.config/yarn/global/node_modules/create-slidev/index.js:122:5) {
  shortMessage: 'Command failed with exit code 1: yarn run dev',
  command: 'yarn run dev',
  escapedCommand: 'yarn run dev',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
✨  Done in 27.10s.
```
**To Reproduce**
1. Run `yarn create slidev`.
2. Input `Project name`.
3. Choose install and start it now.
4. Choose use the yarn agent.
5. See the error.

**Desktop (please complete the following information):**
 - OS: M1 MacBook Pro , Big Sur Version 11.2.3
 - Browser: -
 - Slidev version: 0.20.0

**Comment by antfu** [comment]
Don't think it's due to Slidev itself. Consider upgrade your node to v16 first.

**Comment by originalix** [comment]
> Don't think it's due to Slidev itself. Consider upgrade your node to v16 first.

Thanks. Upgrade node to v16 it's worked for me.👍
