### ISSUE TITLE
Build fail: Rollup failed to resolve import

### ISSUE THREAD

**Issue by keaising** [slidevjs/slidev#287]
**Describe the bug**

I try to integrate slidev into my blog. 

slidev folder at : https://github.com/keaising/keaising.github.io/tree/source/share/git

I can run `npx slidev  --open --remote` and `npx slidev export` successfully in Ubuntu, but `npx slidev build` failed with these error message:

```log
$ npx slidev build


  ●■▲
  Slidev  v0.21.3

  theme   ./theme
  entry   /home/taiga/code/github.com/keaising/keaising.github.io/share/git/slides.md


vite v2.3.8 building for production...
✓ 64 modules transformed.
[vite]: Rollup failed to resolve import "merge.gif" from "../../../../../../../../@slidev/slides/17.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "merge.gif" from "../../../../../../../../@slidev/slides/17.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:45533:19)
    at onwarn (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:45323:13)
    at Object.onwarn (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/rollup/dist/shared/rollup.js:20281:13)
    at ModuleLoader.handleResolveId (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/rollup/dist/shared/rollup.js:19636:26)
    at /home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/rollup/dist/shared/rollup.js:19583:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/rollup/dist/shared/rollup.js:19581:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/rollup/dist/shared/rollup.js:19557:9) {
  watchFiles: [
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/index.html',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/main.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vueuse/head/dist/index.mjs',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/App.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/setup/main.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/routes.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/modules/directives.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/modules/context.ts',
    '/@windicss/devtools',
    '/@slidev/styles',
    '/@windicss/windi-base.css',
    '/@windicss/windi-components.css',
    '/@windicss/windi-utilities.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/styles/vars.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/styles/index.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/styles/code.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/styles/index.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/App.vue?vue&type=script&setup=true&lang.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/setup/root.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vueuse/motion/dist/index.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/vue-router/dist/vue-router.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/internals/Play.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@antfu/utils/dist/index.mjs',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/logic/nav.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/logic/dark.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/env.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/styles/layouts.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/styles/prism.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/styles/shiki.css',
    '/@slidev/routes',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/internals/Presenter.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/styles/layouts-base.css',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vue/shared/dist/shared.esm-bundler.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/vue-demi/lib/index.esm.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vueuse/motion/node_modules/@vueuse/core/dist/index.esm.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vueuse/motion/node_modules/@vueuse/shared/dist/index.esm.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/popmotion/dist/es/index.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@vue/devtools-api/lib/esm/index.js',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/internals/Play.vue?vue&type=script&setup=true&lang.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/internals/Presenter.vue?vue&type=script&setup=true&lang.ts',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/internals/Presenter.vue?vue&type=style&index=0&scoped=true&lang.postcss',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/layouts/end.vue',
    '/@slidev/slides/1.md',
    '/@slidev/slides/2.md',
    '/@slidev/slides/3.md',
    '/@slidev/slides/4.md',
    '/@slidev/slides/5.md',
    '/@slidev/slides/6.md',
    '/@slidev/slides/7.md',
    '/@slidev/slides/8.md',
    '/@slidev/slides/9.md',
    '/@slidev/slides/10.md',
    '/@slidev/slides/11.md',
    '/@slidev/slides/12.md',
    '/@slidev/slides/13.md',
    '/@slidev/slides/14.md',
    '/@slidev/slides/15.md',
    '/@slidev/slides/16.md',
    '/@slidev/slides/17.md',
    '/@slidev/slides/18.md',
    '/@slidev/slides/19.md',
    '/@slidev/slides/20.md',
    '/@slidev/slides/21.md',
    '/@slidev/slides/22.md',
    '/@slidev/slides/23.md',
    '/@slidev/slides/24.md',
    '/@slidev/slides/25.md',
    '/@slidev/slides/26.md',
    '/@slidev/slides/27.md',
    '/@slidev/slides/28.md',
    '/@slidev/slides/29.md',
    '/@slidev/slides/30.md',
    '/@slidev/slides/31.md',
    '/@slidev/slides/32.md',
    '/@slidev/slides/33.md',
    '/@slidev/slides/34.md',
    '/@slidev/slides/35.md',
    '/@slidev/slides/36.md',
    '/@slidev/slides/37.md',
    '/@slidev/slides/38.md',
    '/@slidev/slides/39.md',
    '/@slidev/slides/40.md',
    '/@slidev/slides/41.md',
    '/@slidev/slides/42.md',
    '/@slidev/slides/43.md',
    '/@slidev/slides/44.md',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/layouts/cover.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/layouts/full-image-right.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/layouts/default.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/theme/layouts/quote.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/builtin/CodeHighlightController.vue',
    '/home/taiga/code/github.com/keaising/keaising.github.io/share/git/node_modules/@slidev/client/layouts/center.vue',
    '@vite-icons/carbon/arrow-right',
    '@vite-icons/mdi/alert-circle'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There are some environments:

```shell
Δ node -v
v16.4.0

Δ npm -v
7.18.1

Δ npx -v
7.18.1

Δ npx slidev -v
0.21.3
```

I'm sure the file `merge.gif` in error message exists. Even if I comment the `merge.gif`, the later images in `<img>` such as `*.gif` / `*.png` / `*.jpg` will produce the same error too

**To Reproduce**

You can find Github Action stage named `Build shares`, they have the same error message with build results in my local Ubuntu

1. Github Action with Ubuntu: https://github.com/keaising/keaising.github.io/runs/2920953166?check_suite_focus=true 
2. Github Action with macOS: https://github.com/keaising/keaising.github.io/runs/2920962508?check_suite_focus=true

Github Action config I use as below, you can find full config in https://github.com/keaising/keaising.github.io/blob/source/.github/workflows/publish.yml

```yml
      - name: Build shares
        run: |
          cd share/git
          node --version
          npm --version
          yarn install
          yarn build
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome 
 - Slidev version: 0.21.3

**Comment by keaising** [comment]
I have searched for `[vite]: Rollup failed to resolve import`, many results show that maybe it is a bug of vite, but I'm not familiar with both vite and the integration of slidev and vite.

**Comment by antfu** [comment]
Add leading slash to the path:
https://sli.dev/guide/syntax.html#static-assets
