### ISSUE TITLE
Error: spawn vivaldi ENOENT

### ISSUE THREAD

**Issue by decoherencer** [slidevjs/slidev#288]
**Describe the bug**
stuck with this error during installation itself:

```
Install and start it now? … yes
Choose the agent › npm
added 299 packages, and audited 300 packages in 9s
found 0 vulnerabilities
> dev
> slidev --open
node:events:371
      throw er; // Unhandled 'error' event
      ^
Error: spawn vivaldi ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn vivaldi',
  path: 'vivaldi',
  spawnargs: [ 'http://localhost:3030/' ]
}
Error: Command failed with exit code 1: npm run dev
    at makeError (/home/s/.npm/_npx/c00c242a51a5200e/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/s/.npm/_npx/c00c242a51a5200e/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (/home/s/.npm/_npx/c00c242a51a5200e/node_modules/create-slidev/index.js:122:5) {
  shortMessage: 'Command failed with exit code 1: npm run dev',
```

**To Reproduce**
  running `npm init slidev` under following setup

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux x86_64
 - Browser: Vivaldi 4.0.2312.33
 - Slidev version: v0.21.3
 - npm version: 7.19.0

Thank you

**Comment by antfu** [comment]
Not familiar with Vivaldi, maybe you want to have a look at https://github.com/sindresorhus/open or remove the `--open` arg

**Comment by decoherencer** [comment]
Thanks, I removed the --open arg and able to try it manually

I am not sure how to link the open library and this installation

**Comment by antfu** [comment]
If you are using yarn, you can override it to use link
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it
