### ISSUE TITLE
Build error if content contain import.meta.env

### ISSUE THREAD

**Issue by sdvcrx** [slidevjs/slidev#297]
**Describe the bug**
Build error if content contain `import.meta.env` keyword.

**Error msg**

```
[......]
[rollup-plugin-dynamic-import-variables] Unexpected token (6:45)
file: /@slidev/slides/1.md:6:45
SyntaxError: Unexpected token (6:45)
    at Parser.pp$4.raise (/[...]/node_modules/rollup/dist/shared/rollup.js:16909:13)
    at Parser.pp.unexpected (/[...]/node_modules/rollup/dist/shared/rollup.js:14417:8)
    at Parser.pp.expect (/[...]/node_modules/rollup/dist/shared/rollup.js:14411:26)
    at Parser.pp$3.parseExprList (/[...]/tes/node_modules/rollup/dist/shared/rollup.js:16778:12)
    at Parser.pp$3.parseSubscript (/[...]/node_modules/rollup/dist/shared/rollup.js:16143:25)
    at Parser.pp$3.parseSubscripts (/[...]/node_modules/rollup/dist/shared/rollup.js:16100:24)
    at Parser.pp$3.parseExprSubscripts (/[...]/node_modules/rollup/dist/shared/rollup.js:16084:21)
    at Parser.pp$3.parseMaybeUnary (/[...]/node_modules/rollup/dist/shared/rollup.js:16047:17)
    at Parser.pp$3.parseExprOps (/[...]/node_modules/rollup/dist/shared/rollup.js:15980:19)
    at Parser.pp$3.parseMaybeConditional (/[...]/node_modules/rollup/dist/shared/rollup.js:15963:19) {
  pos: 417,
  loc: Position { line: 6, column: 45 },
  raisedAt: 425,
  code: 'PLUGIN_ERROR',
  plugin: 'rollup-plugin-dynamic-import-variables',
  hook: 'transform',
  id: '/@slidev/slides/1.md',
[......]
```

**To Reproduce**
1. `npm init slidev`
2. Edit `slides.md` file:
```md
---
theme: default
---

# Demo

Build error if content contain `import.meta.env` keyword.
```
3. `slidev build` then throw error

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Slidev version: v0.22.1

**Comment by tonai** [comment]
I can't reproduce.
Maybe this has been fixed.
Can you confirm ?

**Comment by sdvcrx** [comment]
It seems already fixed. Thanks!

**Comment by Rusya13** [comment]
Doesn't look fixed. My content has "import.meta.env" as string. Build is failing with the same error: 
```
vite v2.9.13 building for production...
✓ 28 modules transformed.
[rollup-plugin-dynamic-import-variables] Unexpected token (53:591)
file: /@slidev/routes:53:591
transforming (29) node_modules/@vue/shared/dist/shared.esm-bundler.jsSyntaxError: Unexpected token (53:591)
    at Parser.pp$4.raise (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:19740:13)
    at Parser.pp$9.unexpected (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:17034:8)
    at Parser.pp$9.expect (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:17028:26)
    at Parser.pp$5.parseObj (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:19352:12)
    at Parser.pp$5.parseExprAtom (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:19091:17)
    at Parser.pp$5.parseExprSubscripts (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:18907:19)
    at Parser.pp$5.parseMaybeUnary (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:18873:17)
    at Parser.pp$5.parseExprOps (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:18800:19)
    at Parser.pp$5.parseMaybeConditional (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:18783:19)
    at Parser.pp$5.parseMaybeAssign (/Users/rus/projects/vite-presentation/node_modules/rollup/dist/shared/rollup.js:18750:19) {
  pos: 35478,
  loc: Position { line: 53, column: 591 },
  raisedAt: 35486,
  code: 'PLUGIN_ERROR',
  plugin: 'rollup-plugin-dynamic-import-variables',
  hook: 'transform',
  id: '/@slidev/routes',
```

If I remove "import.meta.env" it builds without any error.
