### ISSUE TITLE
[Feature Request] Allow build with multiple markdown entries

### ISSUE THREAD

**Issue by Shigma** [slidevjs/slidev#317]
**Is your feature request related to a problem? Please describe.**
My team uses slidev to present slides every week, and our project directory looks like this:
```
root
  components
  slides
    20210710.md
    20210717.md
    20210724.md
  package.json
```
I want to build all this slides into a SPA but it seems that slidev only supports building with single entry.

**Describe the solution you'd like**
```
slidev build [file1] [file2]
slidev build [directory]
```

**Describe alternatives you've considered**
N/A

**Comment by antfu** [comment]
Why not just running the script multiple times?

**Comment by Shigma** [comment]
> Why not just running the script multiple times?

Because the assets that slidev generates could have been shared, but it didn't.

```
dist
  assets
    vendor.xxxxxx.js
  index.html
```

What I want is

```
dist
  assets
    vendor.xxxxxx.js (actual "vendor")
    1.xxxxxx.js (for 20210710.md)
    2.xxxxxx.js (for 20210717.md)
    3.xxxxxx.js (for 20210724.md)
  20210710.html
  20210717.html
  20210724.html
```

And each of the generated HTML file have something in common.

**Comment by antfu** [comment]
I guess this could be done by providing multiple input entries to Vite's build. PR Welcome.

**Comment by twitwi** [comment]
cross referencing https://github.com/slidevjs/slidev/issues/479 https://github.com/slidevjs/slidev/issues/505

**Comment by LeonLiuY** [comment]
> I made an implementation that is working You can access at: https://github.com/gabriel-del/slidev All feedbacks are welcome

This no longer works with `@slidev/cli v0.32.3` as it fails to resolve package.json under the `presentations` folder.

**Comment by gabriel-del** [comment]
It works to my friends, it takes some time to buid, maybe 3min, and maybe you need to use npm instead of yarn.
Did you get any error mesage?

**Comment by LeonLiuY** [comment]
Yes I'm using npm.

```
> ./slidev.sh build

Error: Failed to resolve package "/*******/my-slides/presentations/package.json"
    at resolveImportPath (/*******/my-slides/node_modules/@slidev/cli/dist/chunk-JWGORJY6.js:121:11)
    at getPackageJson (/*******/my-slides/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9515:72)
    at getAddons (/*******/my-slides/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9518:33)
    at resolveOptions (/*******/my-slides/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9600:24)
    at async Object.handler (*****/my-slides/node_modules/@slidev/cli/dist/cli.js:172:19)
```

**Comment by Animeshz** [comment]
@gabriel-del I get:

```bash
6:19:30 PM [vite] Internal server error: EMFILE: too many open files, open '/home/animesh/TrashThings/testing/slidev/node_modules/dagre-d3/node_modules/d3-scale-chromatic/src/categorical/Paired.js'
```

**Comment by tonai** [comment]
What this does is just to iterate through the presentations and build each of them independently.
But I fact it will not really solve the problem of build files to be different.
Some files are the same between the build of 2 different slides, and some are different.

For example ,the generated `dist/assets/nav-*.js` contains the content of the slides, so it will automatically be different between two different presentation.
Also some other files will be different simply because they import that `dist/assets/nav-*.js` file for exemple, and because the filename of that imported file is different, then that other file is also different.

We can't really also provide multiple input entries to Vite's build because the entrypoint remains the same for all the slides (that file: https://github.com/slidevjs/slidev/blob/main/packages/client/main.ts).

Maybe one option would be to customize how vite manages and creates the files in the bundle to create files that will contains the maximum of shared code and to isolate specific code that only applies to one presentation (I think it mostly concern virtual imports `/@slidev/routes`, `/@slidev/configs`...etc.).
But I have no idea how this coule be done.

**Comment by tonai** [comment]
I made a PR (https://github.com/slidevjs/slidev/pull/844) to allow the CLI to take multiple entry files when building or exporting.
That won't solve the shared assets problem, but this way it doesn't require external script to work.

**Comment by sor4chi** [comment]
When using multiple builds and expanding as subdirectories, asset loading fails because the asset path is an absolute path.

```
dist
├── sample
│  ├── 404.html
│  ├── _redirects
│  ├── assets
│  └── index.html
└── tutorial
   ├── 404.html
   ├── _redirects
   ├── assets
   └── index.html
```

This picture shows the response result of index.html when accessing /tutorial when the dist is statically hosted using cloudflare pages, etc.

![スクリーンショット 2023-09-12 23 58 41](https://github.com/slidevjs/slidev/assets/80559385/f8130724-4e73-4b9a-8f75-c372191679d5)

**Comment by Kurogoma4D** [comment]
This issue is now a thing of the past, but since it is still open, So I'll comment on it.
I believe the current version (51.6.0) has the following problem when running build on multiple markdowns.

- `dist` is generated in the hierarchy of the first markdown file given
- Assets are not loaded due to differences in paths for each generate
  - This can be resolved with the `--base` option, but you will need to assign each base to multiple markdown files

**Comment by janis-me** [comment]
> `dist` is generated in the hierarchy of the first markdown file [...]

This also does not work if you choose the same filenames for your slides. If you have two `slides.md` files, it will delete the first one, and override it with the second one.

I opened a discussion to talk about creating a proper vite plugin to configure these kind of things and run them as part of a `vite build`. I think this would not be hard to do, but requires the `@slidev/cli` package to export a couple of things

See here: https://github.com/slidevjs/slidev/discussions/2270
