### ISSUE TITLE
template version newer than 0.23.x fails with 'Failed to resolve import "@vueuse/shared"'

### ISSUE THREAD

**Issue by draptik** [slidevjs/slidev#354]
Using the template `npm init slidev@latest` fails on my system for versions 0.23.0 and 0.25.8.

Sorry if I missed something obvious.

```shell
npm init slidev@0.23
# accept all defaults...

6:19:03 PM [vite] Internal server error: Failed to resolve import "@vueuse/shared" from "node_modules/.vite/@vueuse_motion.js?v=867305ac". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/patrick/tmp/slidev-experiments/slidev/node_modules/.vite/@vueuse_motion.js?v=867305ac
  183|
  184|  // node_modules/@vueuse/motion/dist/index.esm-bundler.js
  185|  import { tryOnUnmounted as tryOnUnmounted2, isFunction as isFunction2 } from "@vueuse/shared";
     |                                                                                ^
  186|
  187|  // node_modules/popmotion/node_modules/tslib/tslib.es6.js
      at formatError (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:50163:46)
      at TransformContext.error (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:50159:19)
      at normalizeUrl (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:75881:26)
      at async TransformContext.transform (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:76016:57)
      at async Object.transform (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:50373:30)
      at async transformRequest (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:65414:29)
      at async viteTransformMiddleware (/home/patrick/tmp/slidev-experiments/slidev/node_modules/vite/dist/node/chunks/dep-36bf480c.js:65542:32) (x2)
```

Error doesn't happen when using version 0.22.7.

Maybe a duplicate of https://github.com/slidevjs/slidev/issues/350

**To Reproduce**
1. `mkdir -p tmp/slidev-stuff && cd tmp/slidev-stuff`
2. `npm init slidev@0.23` or `npm init slidev@0.25` (also tried with latest version 0.25.8.)
3. accept all defaults

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser: Chromium
 - Slidev version: 0.23.x to 0.25.8
 - Node version: 16.3.0
 - npm version: 7.15.1

**Comment by antfu** [comment]
Let's keep track in #350
