### ISSUE TITLE
Error on project startup: TypeError: loadTheme is not a function

### ISSUE THREAD

**Issue by AustinGil** [slidevjs/slidev#355]
**Describe the bug**
Error in terminal
```
(node:47546) UnhandledPromiseRejectionWarning: TypeError: loadTheme is not a function
    at /path/to/project/node_modules/@slidev/theme-seriph/setup/shiki.ts:6:19
    at loadSetups (/path/to/project/node_modules/@slidev/cli/dist/chunk-ZK7BUICG.js:693:28)
    at createMarkdownPlugin (/path/to/project/node_modules/@slidev/cli/dist/chunk-ZK7BUICG.js:821:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ViteSlidevPlugin (/path/to/project/node_modules/@slidev/cli/dist/chunk-ZK7BUICG.js:985:26)
    at async createServer (/path/to/project/node_modules/@slidev/cli/dist/chunk-ABJC6OSV.js:10:7)
    at async initServer (/path/to/project/node_modules/@slidev/cli/dist/cli.js:74:14)
```

**To Reproduce**
From the terminal run 
```
npm init slidev
Need to install the following packages:
  create-slidev
Ok to proceed? (y) 

  ●■▲
  Slidev Creator  v0.8.3

✔ Project name: … project-name
  Scaffolding project in project-name ...
  Done.

✔ Install and start it now? … yes
✔ Choose the agent › npm
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: n/a 
 - Slidev version: v0.8.3

**Comment by antfu** [comment]
Ah, you are using the cached creator (pretty old one). Try `npm init slidev@latest`

**Comment by AustinGil** [comment]
Oh, that makes sense. All fixed now.
