### ISSUE TITLE
can not Installation on debian10

### ISSUE THREAD

**Issue by ruaoj** [slidevjs/slidev#376]
- OS:debian10
 - Nodejs:14.18.1
 - npm:8.1.0
 when I use 'npm init slidev@latest' to Installation，here is the error log：

```
Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:3030/' ]
}
Error: Command failed with exit code 1: npm run dev
    at makeError (/root/.npm/_npx/2efb9a200535c2de/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/root/.npm/_npx/2efb9a200535c2de/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async init (/root/.npm/_npx/2efb9a200535c2de/node_modules/create-slidev/index.js:122:5) 
```

**Comment by ruaoj** [comment]
> What if you remove the `--open` in `package.json`'s `scripts.dev` field?
谢谢回复！请问可以用中文交流吗？我的英文实在太烂了，按您说的去掉了open参数，然后用‘npm run dev'的命令跑起来了，但是只能用localhost访问，然后我用nginx 反代了一下，现在有一个问题就是远程访问的过程中网页会不断地自动刷新，请问在不build的情况下可以部署到远程服务器上吗？

**Comment by FossPrime** [comment]
I also had this issue in Replit. The trick was to remove --open from the `npm run dev` script.

If xdg-open is not available it should not be called... this is definitely a bug.

- Code https://replit.com/@fossprime/slidev-xdg-open-bug#package.json
- Live (free so it'll take a second to boot)
  - https://slidev-xdg-open-bug.fossprime.repl.co
