### ISSUE TITLE
Failed to resolve import "@vueuse/shared"

### ISSUE THREAD

**Issue by roamiiing** [slidevjs/slidev#392]
**Describe the bug**
Getting the following error after starting the dev server:

```
3:18:39 PM [vite] Internal server error: Failed to resolve import "@vueuse/shared" from "node_modules/.vite/@vueuse_motion.js?v=ec0efba9". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/roamiiing/dev/anotherslidev/node_modules/.vite/@vueuse_motion.js?v=ec0efba9
  177|
  178|  // node_modules/@vueuse/motion/dist/index.mjs
  179|  import { tryOnUnmounted as tryOnUnmounted2, isFunction as isFunction2 } from "@vueuse/shared";
     |                                                                                ^
  180|
  181|  // node_modules/framesync/dist/es/on-next-frame.mjs
      at formatError (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42189:46)
      at TransformContext.error (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42185:19)
      at normalizeUrl (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:67281:26)
      at async TransformContext.transform (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:67421:57)
      at async Object.transform (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:42396:30)
      at async doTransform (/Users/roamiiing/dev/anotherslidev/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:56797:29)
```

It seems that `@vueuse/shared` package is installed wrongly. In the `package-lock.json` it appears like this:

`node_modules/@vueuse/core/node_modules/@vueuse/shared`

I was able to fix it manually by running `npm i @vueuse/shared`.

**To Reproduce**
1. `npm init slidev@latest`
2. choose npm
3. run the dev server

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.3.1
 - Browser: Google Chrome 95.0.4638.69 (Official Build) (x86_64)
 - Slidev version: 0.27.10

**Comment by antfu** [comment]
You might want to create the issue on https://github.com/vueuse/motion instead.
