### ISSUE TITLE
PDF export aborts on page 3

### ISSUE THREAD

**Issue by yheuhtozr** [slidevjs/slidev#397]
**Describe the bug**

The PDF export command always aborts with error on the page 3, even when I tried with the default sample.

**To Reproduce**
1. `yarn create slidev`
2. `cd slidev-test`
3. `npm i -D playwright-chromium`
4. `yarn slidev export`
5. the error:
  ```
  ●■▲
  Slidev  v0.27.10 

  theme   @slidev/theme-seriph
  entry   /mnt/c/home/slidev-test/slides.md


  ■ rendering █████████░░░░░░░░░░░░░░░░░░░░░ 3/10page.goto: net::ERR_ABORTED; maybe frame was detached?
=========================== logs ===========================
navigating to "http://localhost:12445/3?print", waiting until "networkidle"
============================================================
    at go (/mnt/c/home/slidev-test/node_modules/@slidev/cli/dist/export-D6ZVZTRQ.js:82:16)
    at genPdfBuffer (/mnt/c/home/slidev-test/node_modules/@slidev/cli/dist/export-D6ZVZTRQ.js:107:13)
    at genPageWithClicks (/mnt/c/home/slidev-test/node_modules/@slidev/cli/dist/export-D6ZVZTRQ.js:94:11)
    at exportSlides (/mnt/c/home/slidev-test/node_modules/@slidev/cli/dist/export-D6ZVZTRQ.js:124:13)
    at async Object.handler (/mnt/c/home/slidev-test/node_modules/@slidev/cli/dist/cli.js:272:12) {
  name: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  ```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (WSL1 on Win10)
 - Browser: N/A
 - Slidev version: 0.27.10

**Comment by suica** [comment]
+1

**Comment by xfy196** [comment]
+1

**Comment by GaspardRuan** [comment]
Me too.

**Comment by antfu** [comment]
Closing for now. Feel free to reopen it if it still persist in v0.30

**Comment by twitwi** [comment]
I tried with the latest version and it seems to be working.

For reference, a case of failure is when `<Tweet/>` is used with an invalid `id` (or with none).
