### ISSUE TITLE
Use pnpm to start slidev globally

### ISSUE THREAD

**Issue by yjl9903** [slidevjs/slidev#399]
**Describe the bug**

When using pnpm to install `@slidev/cli` and `@slidev/theme-default` globally, I cannot start the dev server globally.

```
The request url "/Users/xlor/.fnm/node-versions/v16.11.1/installation/pnpm-global/5/node_modules/.pnpm/@slidev+client@0.27.10_vite@2.6.14/node_modules/@slidev/client/main.ts" is outside of Vite serving allow list.

- /Users/xlor/Repos/IncPointerAnalysisNotes/slides
- /Users/xlor/.fnm/node-versions/v16.11.1/installation/pnpm-global/5/node_modules/.pnpm/@slidev+cli@0.27.10/node_modules/@slidev/cli
- /Users/xlor/.fnm/node-versions/v16.11.1/installation/pnpm-global/5/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/client
```

I think this bug is also related to the hoist mode?

**To Reproduce**
1. Create `slides.md`
2. Run `pnpm i -g @slidev/cli @slidev/theme-default`
3. Run `slidev`

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: Edge
 - Slidev version: 0.27.10

**Comment by yjl9903** [comment]
While I am not familiar with the principle of the pnpm, is there any way to support pnpm by default? I hope a more easier way to use slidev with pnpm 👏

**Comment by tonai** [comment]
This seems to be fixed.
Can you confirm ?

**Comment by yjl9903** [comment]
Now global usage is broke by this (there may be no `package.json` when globally using)

https://github.com/slidevjs/slidev/blob/05a93443cd9d0e0e0c60d3dfe7db096ea648700b/packages/slidev/node/addons.ts#L8-L17

**Comment by tonai** [comment]
Do you use any slidev addon ?
What is the error message ?

**Comment by yjl9903** [comment]
> Do you use any slidev addon ? What is the error message ?

```
/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/chunk-JWGORJY6.js:121
    throw new Error(`Failed to resolve package "${importName}"`);
          ^

Error: Failed to resolve package "/Users/xlor/Desktop/package.json"
    at resolveImportPath (/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/chunk-JWGORJY6.js:121:11)
    at getPackageJson (/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9515:72)
    at getAddons (/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9518:33)
    at resolveOptions (/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/chunk-N7XL66RP.js:9600:24)
    at async initServer (/Users/xlor/Library/pnpm/global/5/.pnpm/@slidev+cli@0.32.3/node_modules/@slidev/cli/dist/cli.js:82:21)
```
