### ISSUE TITLE
Could not run composable-vue demo

### ISSUE THREAD

**Issue by tonai** [slidevjs/slidev#450]
**Describe the bug**
When running composable-vue demo I get the following error:
```
11:28:30 [vite] Internal server error: Cannot read properties of undefined (reading 'type')
  Plugin: vite:vue
  File: /home/tocab/Projects/Contrib/slidev/demo/composable-vue/components/NumBox.vue
      at extractEventNames (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vue+compiler-sfc@3.2.26/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4502:19)
      at extractRuntimeEmits (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vue+compiler-sfc@3.2.26/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4492:17)
      at Object.compileScript (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vue+compiler-sfc@3.2.26/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4004:9)
      at resolveScript (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vitejs+plugin-vue@2.0.0_vite@2.7.2+vue@3.2.26/node_modules/@vitejs/plugin-vue/dist/index.js:4303:31)
      at genScriptCode (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vitejs+plugin-vue@2.0.0_vite@2.7.2+vue@3.2.26/node_modules/@vitejs/plugin-vue/dist/index.js:4575:18)
      at transformMain (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vitejs+plugin-vue@2.0.0_vite@2.7.2+vue@3.2.26/node_modules/@vitejs/plugin-vue/dist/index.js:4475:43)
      at TransformContext.transform (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/@vitejs+plugin-vue@2.0.0_vite@2.7.2+vue@3.2.26/node_modules/@vitejs/plugin-vue/dist/index.js:4827:16)
      at Object.transform (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/vite@2.7.2/node_modules/vite/dist/node/chunks/dep-7817f5b4.js:42830:53)
      at async doTransform (/home/tocab/Projects/Contrib/slidev/node_modules/.pnpm/vite@2.7.2/node_modules/vite/dist/node/chunks/dep-7817f5b4.js:57576:29)
```

**To Reproduce**
1. clone this repo 
2. `cd slidev`
3. `pnpm install`
4. `pnpm build`
5. `pnpm demo:composable-vue`
6. Open http://localhost:3030

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.3 LTS (Focal Fossa)
 - Browser: chrome 96.0.4664.110
 - Slidev version: main branch (v0.27.20)
 - node: 16.13.1
 - pnpm: 6.25.1

**Comment by Hyphon** [comment]
same here
