### ISSUE TITLE
Apple Basic Theme does not load

### ISSUE THREAD

**Issue by rebz** [slidevjs/slidev#59]
When attempting to use the `apple-basic` theme I receive the following message in the terminal.
`The theme "slidev-theme-apple-basic" was not found in your project, do you want to install it now?`

I choose `y` to install and receive the following error.
```
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for slidev-theme-apple-basic

(node:25672) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm i slidev-theme-apple-basic
    at makeError (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/chunk-JO7C4JO4.js:5935:17)
    at handlePromise (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/chunk-JO7C4JO4.js:6577:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run2 (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/chunk-JO7C4JO4.js:7501:5)
    at async promptForThemeInstallation (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/chunk-JO7C4JO4.js:7648:3)
    at async resolveOptions (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/chunk-JO7C4JO4.js:7584:9)
    at async initServer (/Users/username/Code/github/test-slidev/node_modules/@slidev/cli/dist/cli.js:68:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have tried the following command as well, `npm install @slidev/theme-apple-basic`.

I can confirm that the package does exist in my `npm_modules`.

I continue to receive the following message each time I try to run `dev`.
`The theme "slidev-theme-apple-basic" was not found in your project, do you want to install it now?`

**Comment by antfu** [comment]
Should be fixed in 0.6.11. Thanks

**Comment by rebz** [comment]
@antfu - The issue is resolved in `0.6.11` however the theme does not appear to be styled. I blew out the repo and re-installed everything fresh.

![image](https://user-images.githubusercontent.com/628385/117757152-857f2580-b1ed-11eb-8e90-93778322d183.png)

Compared to what it should look like.
https://github.com/slidevjs/themes/tree/main/packages/theme-apple-basic

Here is the frontmatter on `slides.md`

```
---
# try also 'default' to start simple
theme: apple-basic
# random image from a curated Unsplash collection by Anthony
# like them? see https://unsplash.com/collections/94734566/slidev
background: https://source.unsplash.com/collection/94734566/1920x1080
# apply any windi css classes to the current slide
class: 'text-center'
# https://sli.dev/custom/highlighters.html
highlighter: shiki
# some information about the slides, markdown enabled
info: |
  ## Slidev Starter Template
  Presentation slides for developers.
  
  Learn more at [Sli.dev](https://sli.dev)
---
```
