### ISSUE TITLE
slidev build failure with `Rollup failed to resolve import "vite-plugin-vue-server-ref/client"`

### ISSUE THREAD

**Issue by knokmki612** [slidevjs/slidev#610]
**Describe the bug**
Get an error message seems caused by vite transforming when exec `slidev dev` `slidev build`

**To Reproduce**
1. Clone this repo https://github.com/tuqulore/vue-3-practices
2. exec `yarn && yarn --cwd docs build`
3. See the error

<summary>log:
<details>

```
$ yarn --cwd docs build
yarn run v1.22.17
$ slidev build


  ●■▲
  Slidev  v0.30.3 

  theme   @slidev/theme-default
  entry   /var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/docs/slides.md


vite v2.9.9 building for production...
✓ 177 modules transformed.
[vite]: Rollup failed to resolve import "vite-plugin-vue-server-ref/client" from "../../../../../../../../@server-reactive/nav".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
transforming (205) components/ClickSample.vueError: [vite]: Rollup failed to resolve import "vite-plugin-vue-server-ref/client" from "../../../../../../../../@server-reactive/nav".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (/var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:41489:19)
    at onwarn (/var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:41305:13)
    at Object.onwarn (/var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:23103:13)
    at ModuleLoader.handleResolveId (/var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22386:26)
    at /var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:22363:26 {
  watchFiles: [
    '/var/home/kimiaki/Workspace/github.com/tuqulore/vue-3-practices/docs/index.html',
(snip)
```

<details>
</summary>

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue 36
 - Browser: Firefox 100.0
 - Slidev version: 0.30.3

**Comment by knokmki612** [comment]
Couldn't figure out why this happens but

- `rm -rf node_modules yarn.lock; npm i; npm run -w docs dev` didn't reproduce the bug
- `rm -rf node_modules package-lock.json; yarn; yarn --cwd docs dev` also didn't reproduce the bug (seems yarn.lock file regeneration resolve the issue)
