### ISSUE TITLE
[vite] Internal server error

### ISSUE THREAD

**Issue by SkyTeamWater** [slidevjs/slidev#645]
**Describe the bug**
After successfully install slidev-cli and do as #635, when open http://localhost:3030 at browser, some warning appear.
```
# bradford @ bradford-laptop in ~/workspace/slidev [18:33:17] 
$ sudo slidev slides.md


  ●■▲
  Slidev  v0.34.2 (global)

  theme   @slidev/theme-seriph
  entry   /home/bradford/workspace/slidev/slides.md

  public slide show   > http://localhost:3030/
  presenter mode      > http://localhost:3030/presenter/
  remote control      > pass --remote to enable

  shortcuts           > restart | open | edit


Element is missing end tag.
18:33:29 [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: /@slidev/slides/1.md
  8  |    </span>
  9  |  </div>
  10 |  <p><a href="https://github.com/slidevjs/slidev" target="_blank" alt="GitHub"
     |      ^
  11 |    class="abs-br m-6 text-xl icon-btn opacity-50 !border-none !hover:text-white"></p>
  12 |    <carbon-logo-github />
      at createCompilerError (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
      at emitError (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1594:29)
      at parseElement (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1146:9)
      at parseChildren (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/usr/local/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
```
Appreciate for help
**To Reproduce**
1. sudo slidev slides.md
2. open http://localhost:3030/

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: 104.0.1293.5 dev (64)
 - Slidev version: v0.34.2

**Comment by Adam-Miao** [comment]
A temporary solution is to delete the enter after `alt="Github"`.

**Comment by SkyTeamWater** [comment]
Thanks! It works!

**Comment by zdl996419** [comment]
想问下您是怎么解决的？

**Comment by heng4fun** [comment]
Same problem:

```shell
slidev


  ●■▲
  Slidev  v0.43.7 (global)

  theme       @slidev/theme-seriph
  css engine  unocss
  entry       /Users/heng4fun/test/slidedev/slides.md

  public slide show   > http://localhost:3030/
  presenter mode      > http://localhost:3030/presenter/
  remote control      > pass --remote to enable

  shortcuts           > restart | open | edit | quit
Element is missing end tag.
Element is missing end tag. (x2)
2:53:29 PM [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: /@slidev/slides/1.md:10:4
  8  |    </span>
  9  |  </div>
  10 |  <p><a href="https://github.com/slidevjs/slidev" target="_blank" alt="GitHub" title="Open in GitHub"
     |      ^
  11 |    class="abs-br m-6 text-xl slidev-icon-btn opacity-50 !border-none !hover:text-white"></p>
  12 |  <carbon-logo-github /></a>
      at createCompilerError (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:18:17)
      at emitError (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1482:5)
      at parseElement (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1031:5)
      at parseChildren (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:844:18)
      at parseElement (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1008:20)
      at parseChildren (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:844:18)
      at parseElement (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1008:20)
      at parseChildren (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:844:18)
      at parseElement (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1008:20)
      at parseChildren (/Users/heng4fun/.nvm/versions/node/v18.15.0/lib/node_modules/@slidev/cli/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:844:18)
Element is missing end tag.
```
