### ISSUE TITLE
Failed to create a proper project with Syntax Error exception

### ISSUE THREAD

**Issue by yasunaz1990** [slidevjs/slidev#676]
**Describe the bug**
I wanted to try the `slidev` and followed the installation process from its documentation.  When I create a project, I got syntax error output on my terminal. 

**To Reproduce**
Steps to reproduce the behavior:n
1. Open your terminal
2. Enter the command `npm install slidev`
3. See the error

```shell
D:\slidejs\demo\slidev\node_modules\vite\dist\node-cjs\publicUtils.cjs:64
    const cache = options.cache ?? new SplitVendorChunkCache();
                                 ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\slidejs\demo\slidev\node_modules\vite\index.cjs:7:31)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slidev@ dev: `slidev --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slidev@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

#### Debug.log content: 
```shell
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle slidev@~predev: slidev@
6 info lifecycle slidev@~dev: slidev@
7 verbose lifecycle slidev@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle slidev@~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\slidejs\demo\slidev\node_modules\.bin;C:\Users\nijat\AppData\Roaming\npm-cache\_npx\27232;C:\Users\nijat\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\nijat\bin;C:\Program Files\Python39\Scripts;C:\Program Files\Python39;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Java\jdk-11.0.15.1\bin;C:\Program Files\Maven\bin;C:\Program Files\nodejs;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\dotnet;C:\Gradle\gradle-6.8.3\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Users\nijat\AppData\Local\Microsoft\WindowsApps;D:\Programs\IntelliJ IDEA Community Edition 2020.3\bin;C:\Users\nijat\AppData\Roaming\npm;C:\Users\nijat\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm 2020.3.3\bin;C:\Users\nijat\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files\Mozilla Firefox;D:\Programs\IntelliJ IDEA Community Edition 2020.3\bin;C:\Program Files\Python39;C:\Program Files\Python39\Lib\site-packages;C:\Program Files\Python39\Lib;C:\Program Files\Python39\DLLs;C:\Users\nijat\AppData\Local\Microsoft\WindowsApps;D:\Programs\IntelliJ IDEA Community Edition 2020.3\bin;C:\Users\nijat\AppData\Roaming\npm;C:\Users\nijat\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm 2020.3.3\bin;C:\Users\nijat\.dotnet\tools;C:\Users\nijat\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\WebStorm 2021.3.3\bin;C:\Users\nijat\AppData\Local\Programs\Hyper\resources\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle slidev@~dev: CWD: D:\slidejs\demo\slidev
10 silly lifecycle slidev@~dev: Args: [ '/d /s /c', 'slidev --open' ]
11 silly lifecycle slidev@~dev: Returned: code: 1  signal: null
12 info lifecycle slidev@~dev: Failed to exec dev script
13 verbose stack Error: slidev@ dev: `slidev --open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid slidev@
15 verbose cwd D:\slidejs\demo\slidev
16 verbose Windows_NT 10.0.22000
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error slidev@ dev: `slidev --open`
22 error Exit status 1
23 error Failed at the slidev@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Desktop (please complete the following information):**
 - OS:   Windows 11 
 - Browser: N/A
 - Slidev version:  latest
 - `npm` version:  6.14.6

**Comment by yasunaz1990** [comment]
Hello guys, just wanted to let you know that I was able to resolve this issue by upgrading the node to the latest version.

**Comment by Aromashen** [comment]
I have same question and update to the latest version but it didn't word
