### ISSUE TITLE
Building is stuck on transforming

### ISSUE THREAD

**Issue by ghaiklor** [slidevjs/slidev#685]
**Describe the bug**
When building the slides, it keeps stuck on these logs:

```text
  ●■▲
  Slidev  v0.35.5

  theme   @slidev/theme-default
  entry   /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/src/2021-06-03-wix-type-challenges.md


vite v3.0.7 building for production...
transforming (249) ../node_modules/@slidev/client/styles/layouts-base.css^C⏎
```

**To Reproduce**

Run the build command on this file https://github.com/ghaiklor/slides.ghaiklor.com/blob/master/src/2021-06-03-wix-type-challenges.md

**Comment by antfu** [comment]
Please shrink the project down to provide a minimal reproduction. Thanks.

**Comment by ghaiklor** [comment]
@antfu it stucks in any case, even with this one:

```markdown
---
title: Type ~~Script~~ Challenges
---
```

**Comment by ghaiklor** [comment]
Anything I can do with debugging? Not much useful info in `env DEBUG`, it stops here:

```text
2022-08-18T17:07:30.287Z vite-plugin-windicss:scan:transform /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/2021-08-18-wix-type-challenges/iframes/monaco/assets/vitesse-dark.39eb2fa3.js
2022-08-18T17:07:30.287Z vite-plugin-windicss:scan:transform /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/2021-08-18-wix-type-challenges/iframes/monaco/assets/vitesse-light.bea81b30.js
2022-08-18T17:07:30.287Z vite-plugin-windicss:scan:transform /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/2021-08-18-wix-type-challenges/iframes/monaco/assets/xml.6de819f4.js
2022-08-18T17:07:30.287Z vite-plugin-windicss:scan:transform /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/2021-08-18-wix-type-challenges/iframes/monaco/assets/yaml.e2cf931f.js
2022-08-18T17:07:31.595Z vite-plugin-windicss:scan:transform /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/2021-11-25-fwdays-v8-under-the-hood/assets/player/main.js
```

The only interesting thing here is that it tries to lookup other JS and CSS files from other artifacts (slides). Here `...fwdays-v8-...` is another slides I have in the root and this is totally different slides, has nothing related with the one I am building

**Comment by ghaiklor** [comment]
My guess: vite-plugin-windicss:scan:transform got a glob that requires it to transform all the files in the project root, even those that are not related. Since the project I have is an archive of slides, I store there markdown files both with the built artifacts. So I guess it keeps doing things it shouldn't?

**Comment by ghaiklor** [comment]
According to the profiler, all the time is spent in `transformGroups` in `@windicss/plugin-utils`:

<img width="1034" alt="Screenshot 2022-08-18 at 20 35 18" src="https://user-images.githubusercontent.com/3625244/185459029-4ce08591-835f-4a33-8f2e-5fdc59b96f70.png">

And there is indeed a while loop, so maybe something wrong with it

**Comment by antfu** [comment]
While I will investigate it on Windi side, you may want to try

```md
---
css: unocss
---
```

**Comment by ghaiklor** [comment]
@antfu with `unocss` it goes further indeed. But got another error with Monaco:

```text


  ●■▲
  Slidev  v0.35.5

  theme   @slidev/theme-default
  entry   /Users/ghaiklor/Library/Projects/slides.ghaiklor.com/src/2021-06-03-wix-type-challenges.md

  ! UnoCSS support is experimental, the styling might break without following semver.
  ! We suggest pinning the version of Slidev when using experimental features.

vite v3.0.7 building for production...
✓ 257 modules transformed.
dist/assets/logo-title-horizontal.96c3c915.png                                119.68 KiB
dist/assets/logo.b72bde5d.png                                                 92.11 KiB
dist/index.html                                                               0.61 KiB
dist/assets/DrawingControls.dcfd207b.js                                       0.21 KiB / gzip: 0.14 KiB
dist/assets/FileSaver.min.7f56e709.js                                         2.98 KiB / gzip: 1.42 KiB
dist/assets/Presenter.1f25be1b.js                                             4.91 KiB / gzip: 2.27 KiB
dist/assets/DrawingLayer.8d90a32b.js                                          0.50 KiB / gzip: 0.35 KiB
dist/assets/DrawingPreview.86989037.js                                        0.09 KiB / gzip: 0.08 KiB
dist/assets/Presenter.f8b7e9e1.css                                            1.96 KiB / gzip: 0.61 KiB
dist/assets/DrawingControls.vue_vue_type_script_setup_true_lang.3f049c71.js   6.92 KiB / gzip: 2.48 KiB
dist/assets/index.a43e6eea.css                                                36.69 KiB / gzip: 7.71 KiB
dist/assets/index.ca83c72f.js                                                 235.74 KiB / gzip: 79.17 KiB
  building for Monaco...

vite v3.0.7 building for production...
✓ 5 modules transformed.
[slidev:monaco-types-loader] Could not load /@slidev-monaco-types/@type-challenges/utils (imported by ../../../../../@slidev/monaco-types): "resolvePackageData" is not supported in CJS build of Vite 3.
Please use ESM or dynamic imports `const { resolvePackageData } = await import('vite')`.
Error: Could not load /@slidev-monaco-types/@type-challenges/utils (imported by ../../../../../@slidev/monaco-types): "resolvePackageData" is not supported in CJS build of Vite 3.
Please use ESM or dynamic imports `const { resolvePackageData } = await import('vite')`.
    at module.exports.<computed> (/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/vite/index.cjs:29:11)
    at Object.load (/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/cli/dist/chunk-ZJSOFQBR.js:955:47)
    at file:///Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/rollup/dist/es/shared/rollup.js:22695:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'slidev:monaco-types-loader',
  hook: 'load',
  watchFiles: [
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/iframes/monaco/index.html',
    'vite/modulepreload-polyfill',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/iframes/monaco/index.ts',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/iframes/monaco/index.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/setup/prettier.ts',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/setup/monaco.ts',
    '/@slidev/styles',
    '/@slidev/monaco-types',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@unocss/reset/package.json',
    '\x00vite/preload-helper',
    '/__uno_preflights.css',
    '/__uno_typography.css',
    '/__uno_shortcuts.css',
    '/__uno.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@unocss/reset/tailwind.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/styles/vars.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/styles/index.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/client/styles/code.css',
    '/Users/ghaiklor/Library/Projects/slides.ghaiklor.com/node_modules/@slidev/theme-default/styles/index.ts',
    '/@slidev-monaco-types/@type-challenges/utils'
  ]
}
```
