### ISSUE TITLE
You may forget to apply app.use(head)

### ISSUE THREAD

**Issue by IanVS** [slidevjs/slidev#706]
**Describe the bug**
I upgraded to 0.36.0, and when I run the dev server, I see this in the browser console:

```
Uncaught Error: You may forget to apply app.use(head)
    at injectHead (index.mjs:107:11)
    at useHead (index.mjs:341:16)
    at setupRoot (root.ts?v=11a5bb6f:18:3)
    at setup (App.vue:4:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7188:29)
    at setupComponent (runtime-core.esm-bundler.js:7143:11)
    at mountComponent (runtime-core.esm-bundler.js:5495:13)
    at processComponent (runtime-core.esm-bundler.js:5470:17)
    at patch (runtime-core.esm-bundler.js:5060:21)
```

I tried building for production, and I get the same error there as well.

**To Reproduce**
1. yarn dev

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave
 - Slidev version: 0.36.0

**Comment by IanVS** [comment]
It seems this was because my theme still had an older version of slidev installed.
