### ISSUE TITLE
Install Failed, Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by winner106** [slidevjs/slidev#725]
**Install Failed**
use `npm init slidev` or `yarn create slidev` to create new project, error.

**To Reproduce**
1. Go to 'cmd' or 'powershell'
2. use `npm init slidev` or `yarn create slidev` to create new project
3. See the error

```powershell
Windows PowerShell

PS C:\Users\Administrator\Downloads> yarn create slidev
yarn create v1.22.1
warning package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-slidev@0.36.6" with binaries:
      - create-slidev
[#######################] 23/23
  ●■▲
  Slidev Creator  v0.36.6

√ Project name: ... slidev
  Scaffolding project in slidev ...
  Done.

√ Install and start it now? ... yes
√ Choose the agent » yarn
yarn install v1.22.1
warning ..\..\package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-android-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/linux-loong64@0.15.10: The platform "win32" is incompatible with this module.
info "@esbuild/linux-loong64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/linux-loong64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info @esbuild/android-arm@0.15.10: The platform "win32" is incompatible with this module.
info "@esbuild/android-arm@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info @esbuild/android-arm@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-android-arm64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-android-arm64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-android-arm64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-arm64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-darwin-arm64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-darwin-arm64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-darwin-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-darwin-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-freebsd-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-32@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-32@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-32@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-arm@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-arm@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-arm64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-arm64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-ppc64le@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-ppc64le@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-ppc64le@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-mips64le@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-mips64le@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-mips64le@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-riscv64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-riscv64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-riscv64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-linux-s390x@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-linux-s390x@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-linux-s390x@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-netbsd-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-netbsd-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-openbsd-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-openbsd-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-sunos-64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-sunos-64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.15.10: The platform "win32" is incompatible with this module.
info "esbuild-freebsd-arm64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-freebsd-arm64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info esbuild-windows-arm64@0.15.10: The CPU architecture "x64" is incompatible with this module.
info "esbuild-windows-arm64@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info esbuild-windows-32@0.15.10: The CPU architecture "x64" is incompatible with this module.
info "esbuild-windows-32@0.15.10" is an optional dependency and failed compatibility check. Excluding it from installation.
warning @slidev/theme-default@0.21.2: The engine "slidev" appears to be invalid.
warning theme-vitesse@0.1.14: The engine "vscode" appears to be invalid.
warning @slidev/theme-seriph@0.21.3: The engine "slidev" appears to be invalid.
[3/4] Linking dependencies...
warning "@slidev/cli > postcss-nested@6.0.0" has unmet peer dependency "postcss@^8.2.14".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 20.69s.
yarn run v1.22.1
warning ..\..\package.json: No license field
$ slidev --open
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Downloads\slidev\pages\multiple-entries.md'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Administrator\\Downloads\\slidev\\pages\\multiple-entries.md'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed with exit code 1: yarn run dev
    at makeError (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\create-slidev\index.js:121:5) {
  shortMessage: 'Command failed with exit code 1: yarn run dev',
  command: 'yarn run dev',
  escapedCommand: 'yarn run dev',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Done in 27.84s.
```

**Desktop (please complete the following information):**
 - Node.js: 16.15
 - OS: Windows_NT x64 10.0.19044
 - Browser:Chrome
 - Slidev version: 0.36.6

**Comment by scguoi** [comment]
same with me.

**Comment by haiker2011** [comment]
same with me.

**Comment by ervinismu** [comment]
same here

**Comment by ervinismu** [comment]
i think, this issue will appear in slidev version [0.36.6](https://www.npmjs.com/package/@slidev/cli/v/0.36.6), when i switch to version [0.36.5](https://www.npmjs.com/package/@slidev/cli/v/0.36.5) using command `npm init slidev@0.36.5` and node `16.0.0`, it worked

**Comment by Luca-Terrazzan** [comment]
I'm willing to open a PR to solve this but I'm unsure on how to reliably test the `npm init` locally

**Comment by murtuzaalisurti** [comment]
> i think, this issue will appear in slidev version [0.36.6](https://www.npmjs.com/package/@slidev/cli/v/0.36.6), when i switch to version [0.36.5](https://www.npmjs.com/package/@slidev/cli/v/0.36.5) using command `npm init slidev@0.36.5` and node `16.0.0`, it worked

this worked for me, thanks!

**Comment by PartyLich** [comment]
There may be a fix in #724, but it is unreleased at the time of writing.

**Comment by lan720** [comment]
> i think, this issue will appear in slidev version [0.36.6](https://www.npmjs.com/package/@slidev/cli/v/0.36.6), when i switch to version [0.36.5](https://www.npmjs.com/package/@slidev/cli/v/0.36.5) using command `npm init slidev@0.36.5` and node `16.0.0`, it worked

Thank you a lot.The question troubled me the whole afternoon.

**Comment by Luca-Terrazzan** [comment]
Why was this closed?

**Comment by Luca-Terrazzan** [comment]
> There may be a fix in #724, but it is unreleased at the time of writing.

to me it seems that #724 is what caused the issue

**Comment by PartyLich** [comment]
@Luca-Terrazzan looks like you deleted your comments. Does that mean you checked the release notes and/or tried 0.36.7 and thus found the answer to your question?

**Comment by Luca-Terrazzan** [comment]
> @Luca-Terrazzan looks like you deleted your comments. Does that mean you checked the release notes and/or tried 0.36.7 and thus found the answer to your question?

Yes sorry, I misinterpreted the build process. My previous comments were clearly wrong so I deleted them to avoid confusions
