### ISSUE TITLE
Version 0.37.0 `npm init` not creating content

### ISSUE THREAD

**Issue by tanepiper** [slidevjs/slidev#768]
**Describe the bug**
When trying to use `npm init slidev` I got the following error:

```
> dev
> slidev --open

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/Users/tapip/github/personal/framework-roadmap/pages/multiple-entries.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/tapip/github/personal/framework-roadmap/pages/multiple-entries.md'
}

Node.js v18.12.1
Error: Command failed with exit code 1: npm run dev
    at makeError (/Users/tapip/.npm/_npx/c00c242a51a5200e/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/tapip/.npm/_npx/c00c242a51a5200e/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/Users/tapip/.npm/_npx/c00c242a51a5200e/node_modules/create-slidev/index.js:121:5) {
  shortMessage: 'Command failed with exit code 1: npm run dev',
  command: 'npm run dev',
  escapedCommand: 'npm run dev',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

When I run `npm init slidev@0.36.11` it works correctly

**To Reproduce**
1. Run `npm init slidev`

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Slidev version: 0.37.0

**Comment by tonai** [comment]
Hum I did not reproduce on my side (using Ubuntu 22.04).
Does the file it is complaining about exist ? (`/Users/tapip/github/personal/framework-roadmap/pages/multiple-entries.md`)
