### ISSUE TITLE
"Try it online" is not working

### ISSUE THREAD

**Issue by BedivereZero** [slidevjs/slidev#769]
**Describe the bug**

**To Reproduce**
1. Go to ['Try It online'](https://sli.dev/guide/#try-it-online)
2. Click on 'sli.dev/new'
3. Right panel show 'Failed to run start command'

Terminal output:

```
~/projects/slidev-grtggz
❯ npm install && npm run dev
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] 🔍  Resolving dependencies
└ Completed in 0.643s
┌ [2/4] 🚚  Fetching dependencies
│ info pruneDeps Excluding 13 dependencies. For more information use `--verbose`.
└ Completed in 3.576s
┌ [3/4] 🔗  Linking dependencies
└ Completed in 3.468s
info security We found `install` scripts which turbo skips for security reasons. For more information see
https://turbo.sh/install-scripts.
├─ esbuild@0.14.54
└─ vue-demi@0.13.6
info Some packages were automatically replaced with polyfills. For more information see https://turbo.sh/polyfills.
└─ esbuild@0.14.54 => esbuild-wasm@0.14.54

success Saved lockfile "package-lock.json"
success Updated "package.json"

success Install finished in 7.873s
$ slidev
✔ The theme "@slidev/theme-seriph" was not found in your project, do you want to install it now? … yes
jsh: command not found: command
[ni] Detected npm but it doesn't seem to be installed.

✔ Would you like to globally install npm (​https://www.npmjs.com/get-npm​)? … yes
Unknown Syntax Error: Unsupported option name ("-g").

$ turbo install [-S,--prod,--save-prod,--save] [-E,--exact,--save-exact] [-P,--peer] [-D,--dev,--save-dev] [-O,--optional,--save-optional] [--no-save] [--audit] [--audit-level #0] [--lockOnly,--package-lock-only] [--packageLock,--package-lock] [--skipOptional,--no-optional] [--skipScripts,--ignore-scripts] [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0] ...
Error: Command failed with exit code 1: npm i -g npm
    at makeError@file:///home/projects/slidev-grtggz/node_modules/ (slidev/cli/dist/chunk-RWZBP7KJ.js:3908:13)
    at handlePromise@file:///home/projects/slidev-grtggz/node_modules/ (slidev/cli/dist/chunk-RWZBP7KJ.js:4509:38)
    at <anonymous> (<anonymous>) {
  shortMessage: 'Command failed with exit code 1: npm i -g npm',
  command: 'npm i -g npm',
  escapedCommand: 'npm i -g npm',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 107.0
 - Slidev version: unknown, provided by official.

**Comment by twitwi** [comment]
I have the same with firefox (stackblitz says it is still alpha, so that might explain) but with chromium it works on my side (linux).

**Comment by tonai** [comment]
Slidev on Stackblitz does not works on firefox.
As @twitwi says it is probably related to the fact that Stackblitz WebContainer are in alpha on firefox (more info here https://blog.stackblitz.com/posts/supporting-firefox/).
