### ISSUE TITLE
Slidev is not working under Stackblitz with Firefox

### ISSUE THREAD

**Issue by edimitchel** [slidevjs/slidev#780]
**Describe the bug**
I would like to solve several issues I found on slidev by bringing easy-to-run reproduction link.
But I just found it's not working using stackblitz.
There is several issue:

First: with the latest version of Slidev (0.37.0, and the introduction of [support custom preparser](https://github.com/slidevjs/slidev/pull/703)) I encounter an issue about package.json of slidev not resolvable.

```
$ slidev
Error: Failed to resolve package "@slidev/client/package.json"
    at resolveImportPath@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/cli/dist/chunk-N6L4BUFD.js:95:11)
    at getClientRoot@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/cli/dist/chunk-ORMJVCP4.js:10250:72)
    at @file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/cli/dist/cli.js:50:36)
    at load/data<@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/parser/dist/fs.js:34:43)
    at parse@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/parser/dist/chunk-72T7ERBC.js:439:26)
    at load@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/parser/dist/fs.js:30:45)
    at <anonymous> (<anonymous>)
```

Repro link: https://stackblitz.com/edit/slidev-eqt8eb?file=package.json
___
Second, by using a previous version, I getting an issue by running slidev cli when it asks to install default theme (which is in the deps list):

```
$ slidev
✔ The theme "@slidev/theme-default" was not found in your project, do you want to install it now? … yes
jsh: command not found: command
[ni] Detected npm but it doesn't seem to be installed.

✔ Would you like to globally install npm (​https://docs.npmjs.com/cli/v8/configuring-npm/install​)? … yes
Unknown Syntax Error: Unsupported option name ("-g").

$ turbo install [-S,--prod,--save-prod,--save] [-E,--exact,--save-exact] [-P,--peer] [-D,--dev,--save-dev] [-O,--optional,--save-optional] [--no-save] [--audit] [--audit-level #0] [--lockOnly,--package-lock-only] [--packageLock,--package-lock] [--skipOptional,--no-optional] [--skipScripts,--ignore-scripts] [--cwd,--prefix #0] [-s,--silent] [--quiet] [-V,--verbose] [--loglevel #0] ...
Error: Command failed with exit code 1: npm i -g npm
    at makeError@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/cli/dist/chunk-C4IMTHZN.js:3972:13)
    at handlePromise@file:///home/projects/slidev-jx9jwl/node_modules/ (slidev/cli/dist/chunk-C4IMTHZN.js:4593:38)
    at <anonymous> (<anonymous>) {
  shortMessage: 'Command failed with exit code 1: npm i -g npm',
  command: 'npm i -g npm',
  escapedCommand: 'npm i -g npm',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
Repro link: https://stackblitz.com/edit/slidev-jx9jwl?file=package.json

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Slidev version: 0.37.0 and 0.36.11

**Comment by tonai** [comment]
This issue is more related to Stackblitz.
on stackblitz with firefox you have a notice that says:

> WebContainers for Firefox are in alpha

see https://blog.stackblitz.com/posts/supporting-firefox/

**Comment by davidbludlow** [comment]
How about you fix this by changing it so that https://sli.dev/new uses codesandbox.io instead of stackblitz. Using Firefox is a non-negotiable requirement for me. Codesandbox works just fine with Firefox.
