### ISSUE TITLE
Error: Cannot find module '@slidev/parser/fs' 

### ISSUE THREAD

**Issue by LiZheGuang** [slidevjs/slidev#81]
npm init slidev  That's the performance、。

Error: Cannot find module '@slidev/parser/fs'
Require stack:
- /Users/lizheguang/zheGuangCode/slidev/node_modules/@slidev/cli/dist/chunk-AMXRPYUL.js
- /Users/lizheguang/zheGuangCode/slidev/node_modules/@slidev/cli/dist/chunk-I6I6DDEX.js
- /Users/lizheguang/zheGuangCode/slidev/node_modules/@slidev/cli/dist/cli.js
- /Users/lizheguang/zheGuangCode/slidev/node_modules/@slidev/cli/bin/slidev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/lizheguang/zheGuangCode/slidev/node_modules/@slidev/cli/dist/chunk-AMXRPYUL.js:217:12)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
 
node: v12.16.3

**Comment by antfu** [comment]
We only support node v14 and onward, as node v12 is out of LTS. Please upgrade, thanks.
