### ISSUE TITLE
slidev.ps1 command error

### ISSUE THREAD

**Issue by huigang39** [slidevjs/slidev#814]
**Describe the problem**
I have installed slidev globally and when I use the slidev.ps1 command, the program reports an error and I have changed multiple themes to no avail.

```
√ The theme "@slidev/theme-apple-basic" is not found in your project, do you want to install it now? ... Yes

7 packages reviewed in 4s so far

4 packages are looking for funding
  Run "npm fund" for details

0 vulnerabilities found
C:\Users\huigang39\scoop\persist\nodejs\bin\node_modules\@slidevcli\dist\chunk-OVFYMGU6.js:95
    throw new Error(`Failed to resolve package "${importName}"`).
          ^

Error. Failed to resolve package "@slidev/theme-apple-basic/package.json".
    at resolveImportPath (C:\Users\huigang39\scooppersist\nodejs\bin\node_modules\@slidev\cli\dist\chunk-OVFYMGU6.js:95:11)
    at getRoot (C:\Users\huigang39\scoop\persist\nodejs\bin\node_modules\@slidev\cli\dist\chunk-CGI3XOIB.js:10272:72)
    at getThemeRoots (C:\Users\huigang39\scoop\persist\nodejs\bin\node_modules\@slidev\cli\dist\chunk-CGI3XOIB.js:10262:11)
    at resolveOptions (C:\Users\huigang39\scoop\persist\nodejsbin\node_modules\@slidev\cli\dist\chunk-CGI3XOIB.js:10298:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async initServer (C:\Users\huigang39\scoop\persist\nodejs\bin\node_modules\@slidev\cli\dist\cli.js:108:23)

Node.js v19.3.0
```

![image](https://user-images.githubusercontent.com/63324254/211536887-6d375247-c9eb-4413-8459-2576a2a508b5.png)

**To reproduce**
Type slidev.ps1 directly

**Desktop (please fill in the following information):**
 - Window 11
 - Edge
 - 0.38.3

Translated with www.DeepL.com/Translator (free version)

**Comment by huigang39** [comment]
#635 This is useful
