### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by vltansky** [slidevjs/slidev#877]
**Describe the bug**
Cant init project with pnpm

**To Reproduce**
1. `npm init slidev`
2. choose pnpm
```
Downloading registry.npmjs.org/monaco-editor/0.33.0: 14.4 MB/14.4 MB, done
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Packages: +484
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/vl.tansky/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 505, reused 147, downloaded 337, added 484, done
node_modules/.pnpm/vue-demi@0.13.11_vue@3.2.47/node_modules/vue-demi: Running postinstall script, done in 92ms
node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running postinstall script, done in 1.1s

dependencies:
+ @slidev/cli 0.40.2
+ @slidev/theme-default 0.21.2
+ @slidev/theme-seriph 0.21.3

 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @slidev/cli
  ├─┬ postcss-nested
  │ └── ✕ missing peer postcss@^8.2.14
  ├─┬ vite-plugin-remote-assets
  │ └── ✕ unmet peer vite@"^2.0.0 || ^3.0.0": found 4.1.1 in @slidev/cli
  └─┬ vite-plugin-vue-server-ref
    └── ✕ unmet peer vite@"^2.0.0 || ^3.0.0": found 4.1.1 in @slidev/cli
Peer dependencies that should be installed:
  postcss@^8.2.14  
Error: Command failed with exit code 1: pnpm install
    at makeError (/Users/vl.tansky/.npm/_npx/c00c242a51a5200e/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/vl.tansky/.npm/_npx/c00c242a51a5200e/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/Users/vl.tansky/.npm/_npx/c00c242a51a5200e/node_modules/create-slidev/index.js:120:5) {
  shortMessage: 'Command failed with exit code 1: pnpm install',
  command: 'pnpm install',
  escapedCommand: 'pnpm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Worked with npm

**Desktop (please complete the following information):**
 - OS: MacOs
 - NodeJS: v18.12.1
 - pnpm version: 7.1.0
 - npm version: 8.19.2
 - Browser: Terminal
 - Slidev version: v0.40.2

**Comment by tonai** [comment]
Can't reproduce on my side (using `npm init slidev@latest`):
```
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
Packages: +483
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/tocab/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 505, reused 483, downloaded 0, added 483, done

dependencies:
+ @slidev/cli 0.40.2
+ @slidev/theme-default 0.21.2
+ @slidev/theme-seriph 0.21.3

 WARN  Issues with peer dependencies found
.
└─┬ @slidev/cli 0.40.2
  ├─┬ vite-plugin-remote-assets 0.3.0
  │ └── ✕ unmet peer vite@"^2.0.0 || ^3.0.0": found 4.1.1 in @slidev/cli
  └─┬ vite-plugin-vue-server-ref 0.3.0
    └── ✕ unmet peer vite@"^2.0.0 || ^3.0.0": found 4.1.1 in @slidev/cli

Done in 12.3s
```

Using `pnpm` version 7.23.0 and `npm` version 8.19.2.
Can you try upgrading pnpm ?

**Comment by vltansky** [comment]
Yep, upgrading pnpm solved it. I had some troubles with pnpm installation, so yesterday when I tried to update it before opening the issue, it didn't update. Thanks :)
