### ISSUE TITLE
Build error when "monaco:true": "Cannot read properties of null (reading 'hasEffectsOnInteractionAtPath')"

### ISSUE THREAD

**Issue by angelbt91** [slidevjs/slidev#887]
**Describe the bug**
When having `monaco: true` and at least one codeblock that uses monaco on `./slides.md`, then running `npm run build`, build fails with the following message:

`TypeError: Cannot read properties of null (reading 'hasEffectsOnInteractionAtPath')`

Full terminal output:

```
> build
> slidev build

  ●■▲
  Slidev  v0.40.2 

  theme   @slidev/theme-default
  entry   /home/angel/Documents/Projects/Nuclio/typescript-slides/slides.md

vite v4.1.1 building for production...
transforming (194) node_modules/popmotion/dist/es/animations/utils/detect-animation-from-options.mjs[plugin:vite:esbuild] This assignment will throw because "clicksElements" is a constant
33 |      _createVNode(PrintSlideClick, {
34 |        "clicks-elements": clicksElements,
35 |        "onUpdate:clicksElements": _cache[0] || (_cache[0] = ($event: any) => ((clicksElements) = $event)),
   |                                                                                ^
36 |        clicks: 0,
37 |        nav: _unref(nav),

✓ 295 modules transformed.
dist/index.html                                   1.31 kB
dist/assets/logo-b72bde5d.png                    94.32 kB
dist/assets/logo-title-horizontal-96c3c915.png  122.56 kB
dist/assets/Presenter-bfcdcc16.css                2.13 kB │ gzip:  0.63 kB
dist/assets/nav-38c44537.css                      2.34 kB │ gzip:  0.77 kB
dist/assets/index-9ceecc96.css                   45.02 kB │ gzip:  9.43 kB
dist/assets/DrawingLayer-a1a67ebe.js              0.65 kB │ gzip:  0.45 kB
dist/assets/NoteDisplay-745903f2.js               1.05 kB │ gzip:  0.52 kB
dist/assets/PresenterPrint-71de8b85.js            1.61 kB │ gzip:  0.94 kB
dist/assets/FileSaver.min-17c85779.js             3.07 kB │ gzip:  1.47 kB
dist/assets/NotesView-b17bbc04.js                 3.28 kB │ gzip:  1.49 kB
dist/assets/Presenter-1b5e636c.js                 4.84 kB │ gzip:  2.28 kB
dist/assets/DrawingControls-ea8dafa3.js           7.13 kB │ gzip:  2.68 kB
dist/assets/index-67d67616.js                    14.84 kB │ gzip:  5.56 kB
dist/assets/index-734adb1f.js                    51.00 kB │ gzip: 19.51 kB
dist/assets/nav-1862c598.js                     287.56 kB │ gzip: 95.44 kB
  building for Monaco...

vite v4.1.1 building for production...
✓ 861 modules transformed.
transforming (866) ../../../../monaco-editor/esm/vs/language/typescript/ts.worker.jsCannot read properties of null (reading 'hasEffectsOnInteractionAtPath')
TypeError: Cannot read properties of null (reading 'hasEffectsOnInteractionAtPath')
    at Identifier.hasEffectsOnInteractionAtPath (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:7991:92)
    at MemberExpression.hasEffectsOnInteractionAtPath (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:9212:32)
    at MemberExpression.hasEffectsAsAssignmentTarget (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:9202:18)
    at AssignmentExpression.hasEffects (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:8608:51)
    at ExpressionStatement.hasEffects (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:5735:28)
    at Program.hasEffects (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:11439:22)
    at Program.hasCachedEffects (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:11434:44)
    at Module.hasEffects (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:13335:75)
    at addSideEffectDependencies (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:13675:72)
    at Module.addRelevantSideEffectDependencies (file:///home/angel/Documents/Projects/Nuclio/typescript-slides/node_modules/rollup/dist/es/shared/rollup.js:13682:9)
```

**To Reproduce**
1. Create a new Slidev project with `npm init slidev`
2. Wait until project is created and all deps are installed.
3. Add on 2nd line of `slides.md` the following: `monaco: true`
4. Add a codeblock on `slides.md` that uses monaco. Or, instead of adding a codeblock, you can edit the example one to use monaco, by modifying line 129 as  *```ts {monaco}*

5. Run `npm run build` in the console

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox 109.0.1 (64-bit) and Chrome 110.0.5481.77 (Official Build) (64-bit)
 - Slidev version: Tested with both 0.40.2 and 0.40.3

**Comment by haodd0216** [comment]
did you solve this problem

**Comment by angelbt91** [comment]
> did you solve this problem

Sadly no, I'm still exporting the slides without the live Monaco editor.

**Comment by sosensible** [comment]
I got a similar issue with these details. Note that I did not modify anything beyond creating the project and running build.

```
vite v4.1.4 building for production...
transforming (260) node_modules\@slidev\parser\dist\core.mjs[plugin:vite:esbuild] This assignment will throw because "clicksElements" is a constant
33 |      _createVNode(PrintSlideClick, {
34 |        "clicks-elements": clicksElements,
35 |        "onUpdate:clicksElements": _cache[0] || (_cache[0] = ($event: any) => ((clicksElements) = $event)),
   |                                                                                ^
36 |        clicks: 0,
37 |        nav: _unref(nav),

transforming (300) node_modules\@slidev\client\internals\PrintSlideClick.vue
```
