### ISSUE TITLE
Slidev 0.40.5 breaks static assets with customized public directory

### ISSUE THREAD

**Issue by Hydragyrum** [slidevjs/slidev#932]
**Describe the bug**
I have a presentation created with Slidev 0.40.3 with a base path set, and a static assets directory set to `/static` via the vite config. When building it works fine. 

Updating to 0.40.5, with zero changes to code, nor config, the build fails as it can no longer find my static assets at build time.
Logs as follows:

```
$ pnpm build --base /dungeon-master-prez/ --out public
> dungeon-master@ build /builds/Hydragyrum/dungeon-master-prez
> slidev build "--base" "/dungeon-master-prez/" "--out" "public"
  ●■▲
  Slidev  v0.40.5 
  theme   slidev-theme-hydra-conf
  entry   /builds/Hydragyrum/dungeon-master-prez/slides.md
vite v4.2.1 building for production...
transforming...
/fonts/BigShouldersInlineDisplay.ttf referenced in /builds/Hydragyrum/dungeon-master-prez/styles/base.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
/fonts/Nunito.ttf referenced in /builds/Hydragyrum/dungeon-master-prez/styles/base.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
/fonts/FiraCode.ttf referenced in /builds/Hydragyrum/dungeon-master-prez/styles/base.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 87 modules transformed.
✓ built in 3.00s
[vite]: Rollup failed to resolve import "/img/devoxx-france-light.png" from "/@slidev/slides/1.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "/img/devoxx-france-light.png" from "/@slidev/slides/1.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46368:19)
    at onwarn (file:///builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46138:13)
    at Object.onwarn (file:///builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:25149:13)
    at ModuleLoader.handleInvalidResolvedId (file:///builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:23784:26)
    at file:///builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:23744:26 {
  watchFiles: [
    '/builds/Hydragyrum/dungeon-master-prez/index.html',
    '\x00vite/modulepreload-polyfill',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/main.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue@3.2.47/node_modules/vue/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+head@1.1.23_vue@3.2.47/node_modules/@vueuse/head/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue@3.2.47/node_modules/vue/dist/vue.runtime.esm-bundler.js',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+head@1.1.23_vue@3.2.47/node_modules/@vueuse/head/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/App.vue',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/setup/main.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/routes.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/modules/directives.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/modules/context.ts',
    '/@slidev/styles',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unocss+reset@0.50.6/node_modules/@unocss/reset/package.json',
    '/__uno_preflights.css',
    '/__uno_typography.css',
    '/__uno_shortcuts.css',
    '/__uno.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unocss+reset@0.50.6/node_modules/@unocss/reset/tailwind.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/styles/vars.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/styles/index.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/styles/code.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/styles/transitions.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/slidev-theme-hydra-conf@0.0.5/node_modules/slidev-theme-hydra-conf/styles/index.ts',
    '/builds/Hydragyrum/dungeon-master-prez/styles/index.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+runtime-dom@3.2.47/node_modules/@vue/runtime-dom/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+runtime-dom@3.2.47/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+vue@1.1.25_vue@3.2.47/node_modules/@unhead/vue/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+dom@1.1.25/node_modules/@unhead/dom/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+ssr@1.1.25/node_modules/@unhead/ssr/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+vue@1.1.25_vue@3.2.47/node_modules/@unhead/vue/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+dom@1.1.25/node_modules/@unhead/dom/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+ssr@1.1.25/node_modules/@unhead/ssr/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/App.vue?vue&type=script&setup=true&lang.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+motion@2.0.0-beta.27_vue@3.2.47/node_modules/@vueuse/motion/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue-starport@0.3.0/node_modules/vue-starport/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@antfu+utils@0.7.2/node_modules/@antfu/utils/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/package.json',
    '\x00plugin-vue:export-helper',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+motion@2.0.0-beta.27_vue@3.2.47/node_modules/@vueuse/motion/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue-starport@0.3.0/node_modules/vue-starport/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@antfu+utils@0.7.2/node_modules/@antfu/utils/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/logic/nav.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/constants.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/logic/dark.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/composables/useContext.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/internals/Play.vue',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/internals/Print.vue',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/internals/PresenterPrint.vue',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/internals/NotesView.vue',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/internals/Presenter.vue',
    '/@slidev/routes',
    '/@slidev/configs',
    '\x00vite/preload-helper',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/slidev-theme-hydra-conf@0.0.5/node_modules/slidev-theme-hydra-conf/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/slidev-theme-hydra-conf@0.0.5/node_modules/slidev-theme-hydra-conf/styles/layout.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/slidev-theme-hydra-conf@0.0.5/node_modules/slidev-theme-hydra-conf/styles/code.css',
    '/builds/Hydragyrum/dungeon-master-prez/styles/base.css',
    '/builds/Hydragyrum/dungeon-master-prez/styles/layouts.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/setup/root.ts',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/styles/layouts-base.css',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+runtime-core@3.2.47/node_modules/@vue/runtime-core/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+shared@3.2.47/node_modules/@vue/shared/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+runtime-core@3.2.47/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vue+shared@3.2.47/node_modules/@vue/shared/dist/shared.esm-bundler.js',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/unhead@1.1.25/node_modules/unhead/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+shared@1.1.25/node_modules/@unhead/shared/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/unhead@1.1.25/node_modules/unhead/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+vue@1.1.25_vue@3.2.47/node_modules/@unhead/vue/dist/shared/vue.bc44c3fa.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@unhead+shared@1.1.25/node_modules/@unhead/shared/dist/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@slidev+client@0.40.5_postcss@8.4.21_vite@4.2.1/node_modules/@slidev/client/layouts/end.vue',
    '/@slidev/slides/1.md',
    '/@slidev/slides/2.md',
    '/@slidev/slides/3.md',
    '/@slidev/slides/4.md',
    '/@slidev/slides/5.md',
    '/@slidev/slides/6.md',
    '/@slidev/slides/7.md',
    '/@slidev/slides/8.md',
    '/@slidev/slides/9.md',
    '/@slidev/slides/10.md',
    '/@slidev/slides/11.md',
    '/@slidev/slides/12.md',
    '/@slidev/slides/13.md',
    '/@slidev/slides/14.md',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/defu@6.1.2/node_modules/defu/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+core@9.13.0_vue@3.2.47/node_modules/@vueuse/core/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+shared@9.13.0_vue@3.2.47/node_modules/@vueuse/shared/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/framesync@6.1.2/node_modules/framesync/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/popmotion@11.0.5/node_modules/popmotion/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/style-value-types@5.1.2/node_modules/style-value-types/package.json',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/defu@6.1.2/node_modules/defu/dist/defu.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+core@9.13.0_vue@3.2.47/node_modules/@vueuse/core/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/@vueuse+shared@9.13.0_vue@3.2.47/node_modules/@vueuse/shared/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/framesync@6.1.2/node_modules/framesync/dist/es/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/popmotion@11.0.5/node_modules/popmotion/dist/es/index.mjs',
    '/builds/Hydragyrum/dungeon-master-prez/node_modules/.pnpm/style-value-types@5.1.2/node_modules/style-value-types/dist/es/index.mjs',
    ... 104 more items
  ]
}
 ELIFECYCLE  Command failed with exit code 1.
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

I will attempt to reproduce with a demo example shortly, but it seems that a recent change to fix an entry directory may have broken this use case. (#904)

**To Reproduce**
1. Customize base path and publicDir in `vite.config.ts`
2. `pnpm build`
3. See the error

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Browser: Firefox or Chromium
 - Slidev version: 0.40.5 (maybe .4 as well)

**Comment by Hydragyrum** [comment]
It seems that changing the publicDir breaks the build process, reproducible scenario here:

https://github.com/Hydragyrum/slidev-932-repro

**Comment by Hydragyrum** [comment]
For the record, I need to be able to store static assest outside of the `public` directory as gitlab ci will use `public` as the landing point for its pages.

**Comment by eric-burel** [comment]
I have the same error but without a custom `public` directory. I don't build often (PDF export, running locally work fine) so not sure when it started. Am I expected to store images in the "public" folder? So far I've been storing them in "/img" at the root and it worked well.
