### ISSUE TITLE
Cannot use css mode `windicss` in default project

### ISSUE THREAD

**Issue by tkgregory** [slidevjs/slidev#994]
When creating the default Slidev project, it uses `css` mode *unocss*. This is working great, and thanks for your hard work.

However, when I remove the `css` option from *slides.md*, to use the default *windicss*, I receive this error.

```
[postcss] Cannot read properties of undefined (reading 'config')
[postcss] Cannot read properties of undefined (reading 'config') (x2)      
[postcss] Cannot read properties of undefined (reading 'config') (x3)      
...
11:07:52 [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'config')
  Plugin: vite:css
  File: /@windicss/windi-components.css
      at getTailwindConfig (C:\workspace\gradle-hero-website\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:87:62)
      at C:\workspace\gradle-hero-website\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:99:92
      at C:\workspace\gradle-hero-website\node_modules\tailwindcss\lib\processTailwindFeatures.js:48:11
      at plugins (C:\workspace\gradle-hero-website\node_modules\tailwindcss\lib\plugin.js:38:63)
      at LazyResult.runOnRoot (C:\workspace\gradle-hero-website\slidev\node_modules\postcss\lib\lazy-result.js:339:16)
      at LazyResult.runAsync (C:\workspace\gradle-hero-website\slidev\node_modules\postcss\lib\lazy-result.js:393:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async compileCSS (file:///C:/workspace/gradle-hero-website/slidev/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:38483:25)
      at async TransformContext.transform (file:///C:/workspace/gradle-hero-website/slidev/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:37919:56)
      at async Object.transform (file:///C:/workspace/gradle-hero-website/slidev/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42883:30)
```

1. Run `npm init slidev`
2. Use the following options:
```
Slidev Creator  v0.40.2

√ Project name: ... slidev
  Scaffolding project in slidev ...
  Done.

√ Install and start it now? ... yes
√ Choose the agent » npm
```
4. See that the slides are working in a browser
5. Remove the line `css: unocss` from *slides.md*
6. See the browser window turns white and the above error shows in the console

 - OS: Windows 11
 - Browser: Chrome
 - Slidev version: v0.40.2 (I have also observed the same problem with Slidev v0.40.3)

The expectation is that the default `css` mode *windicss* should be supported. 
It would also be helpful to know why  `npm init slidev` sets up a project using *unocss* mode.

**Comment by xu4wang** [comment]
same error here.
